import { TouchableNativeFeedbackComponent } from "react-native";

export const BussinesImages = {
  agenda: require("../../assets/Bussines/agenda.png"),
  agenda2: require("../../assets/Bussines/agenda2.png"),
  arquivo: require("../../assets/Bussines/arquivo.png"),
  aula1: require("../../assets/Bussines/aula1.png"),
  aula2: require("../../assets/Bussines/aula2.png"),
  aula3: require("../../assets/Bussines/aula3.png"),
  aula4: require("../../assets/Bussines/aula4.png"),
  aula5: require("../../assets/Bussines/aula5.png"),
  call: require("../../assets/Bussines/call.png"),
  carta: require("../../assets/Bussines/carta.png"),
  celebro: require("../../assets/Bussines/celebro.png"),
  company: require("../../assets/Bussines/company.png"),
  config: require("../../assets/Bussines/config.png"),
  confuso: require("../../assets/Bussines/confuso.png"),
  confuso2: require("../../assets/Bussines/confuso2.png"),
  conversa: require("../../assets/Bussines/conversa.png"),
  conversa2: require("../../assets/Bussines/conversa2.png"),
  diresao: require("../../assets/Bussines/diresao.png"),
  email: require("../../assets/Bussines/email.png"),
  email2: require("../../assets/Bussines/email2.png"),
  envelope: require("../../assets/Bussines/envelope.png"),
  estrela: require("../../assets/Bussines/estrela.png"),
  fone: require("../../assets/Bussines/fone.png"),
  hi: require("../../assets/Bussines/hi.png"),
  hi2: require("../../assets/Bussines/hi2.png"),
  ideia: require("../../assets/Bussines/ideia.png"),
  ideia2: require("../../assets/Bussines/ideia2.png"),
  ligacao: require("../../assets/Bussines/ligacao.png"),
  livro: require("../../assets/Bussines/livro.png"),
  lupa: require("../../assets/Bussines/lupa.png"),
  lupa2: require("../../assets/Bussines/lupa2.png"),
  material: require("../../assets/Bussines/material.png"),
  menina: require("../../assets/Bussines/menina.png"),
  menina2: require("../../assets/Bussines/menina2.png"),
  menino: require("../../assets/Bussines/menino.png"),
  menino2: require("../../assets/Bussines/menino2.png"),
  meninolivro: require("../../assets/Bussines/meninolivro.png"),
  mensagem: require("../../assets/Bussines/mensagem.png"),
  mensagem2: require("../../assets/Bussines/mensagem2.png"),
  obrigado: require("../../assets/Bussines/obrigado.png"),
  recap: require("../../assets/Bussines/recap.png"),
  relogio: require("../../assets/Bussines/relogio.png"),
  reuniao: require("../../assets/Bussines/reuniao.png"),
  secretaria: require("../../assets/Bussines/secretaria.png"),
  secretario: require("../../assets/Bussines/secretario.png"),
  sorry: require("../../assets/Bussines/sorry.png"),
  storm: require("../../assets/Bussines/storm.png"),
  telefone: require("../../assets/Bussines/telefone.png"),
  texto: require("../../assets/Bussines/texto.png"),
  trabalho: require("../../assets/Bussines/trabalho.png"),
  tradutor: require("../../assets/Bussines/tradutor.png"),
  tradutor2: require("../../assets/Bussines/tradutor2.png"),
  what: require("../../assets/Bussines/what.png"),
  who: require("../../assets/Bussines/who.png"),
};

export const CursosImages = {
  bussines: require("../../assets/Cursos/bussines.jpg"),
  mundo: require("../../assets/Cursos/mundo.jpg"),
  pronuncia: require("../../assets/Cursos/pronuncia.jpg"),
  viagem: require("../../assets/Cursos/viagem.jpg"),
};
