export const BussinesImages = {
  agenda: require("../../assets/Bussines/agenda.png"),
  agenda2: require("../../assets/Bussines/agenda2.png"),
  arquivo: require("../../assets/Bussines/arquivo.png"),
  aula1: require("../../assets/Bussines/aula1.png"),
  aula2: require("../../assets/Bussines/aula2.png"),
  aula3: require("../../assets/Bussines/aula3.png"),
  aula4: require("../../assets/Bussines/aula4.png"),
  aula5: require("../../assets/Bussines/aula5.png"),
  call: require("../../assets/Bussines/call.png"),
  carta: require("../../assets/Bussines/carta.png"),
  celebro: require("../../assets/Bussines/celebro.png"),
  company: require("../../assets/Bussines/company.png"),
  config: require("../../assets/Bussines/config.png"),
  confuso: require("../../assets/Bussines/confuso.png"),
  confuso2: require("../../assets/Bussines/confuso2.png"),
  conversa: require("../../assets/Bussines/conversa.png"),
  conversa2: require("../../assets/Bussines/conversa2.png"),
  diresao: require("../../assets/Bussines/diresao.png"),
  email: require("../../assets/Bussines/email.png"),
  email2: require("../../assets/Bussines/email2.png"),
  envelope: require("../../assets/Bussines/envelope.png"),
  estrela: require("../../assets/Bussines/estrela.png"),
  fone: require("../../assets/Bussines/fone.png"),
  hi: require("../../assets/Bussines/hi.png"),
  hi2: require("../../assets/Bussines/hi2.png"),
  ideia: require("../../assets/Bussines/ideia.png"),
  ideia2: require("../../assets/Bussines/ideia2.png"),
  ligacao: require("../../assets/Bussines/ligacao.png"),
  livro: require("../../assets/Bussines/livro.png"),
  lupa: require("../../assets/Bussines/lupa.png"),
  lupa2: require("../../assets/Bussines/lupa2.png"),
  material: require("../../assets/Bussines/material.png"),
  menina: require("../../assets/Bussines/menina.png"),
  menina2: require("../../assets/Bussines/menina2.png"),
  menino: require("../../assets/Bussines/menino.png"),
  menino2: require("../../assets/Bussines/menino2.png"),
  meninolivro: require("../../assets/Bussines/meninolivro.png"),
  mensagem: require("../../assets/Bussines/mensagem.png"),
  mensagem2: require("../../assets/Bussines/mensagem2.png"),
  obrigado: require("../../assets/Bussines/obrigado.png"),
  recap: require("../../assets/Bussines/recap.png"),
  relogio: require("../../assets/Bussines/relogio.png"),
  reuniao: require("../../assets/Bussines/reuniao.png"),
  secretaria: require("../../assets/Bussines/secretaria.png"),
  secretario: require("../../assets/Bussines/secretario.png"),
  sorry: require("../../assets/Bussines/sorry.png"),
  storm: require("../../assets/Bussines/storm.png"),
  telefone: require("../../assets/Bussines/telefone.png"),
  texto: require("../../assets/Bussines/texto.png"),
  trabalho: require("../../assets/Bussines/trabalho.png"),
  tradutor: require("../../assets/Bussines/tradutor.png"),
  tradutor2: require("../../assets/Bussines/tradutor2.png"),
  what: require("../../assets/Bussines/what.png"),
  who: require("../../assets/Bussines/who.png"),
};

export const IC = {
  semimg: require("../../assets/IC/semimg.jpg"),
  slide1: require("../../assets/IC/IC01 slide1.png"),
  slide6: require("../../assets/IC/IC01 slide6.png"),
  slide6p2: require("../../assets/IC/IC01 slide6p2.png"),
  A1S2: require("../../assets/IC/A1S2.jpg"),
  A1S3: require("../../assets/IC/A1S3.jpg"),
  A1S10: require("../../assets/IC/A1S10.jpg"),
  A2S1: require("../../assets/IC/A2S1.png"),
  A2S2: require("../../assets/IC/A2S2.jpg"),
  A2S4: require("../../assets/IC/A2S4.png"),
  A2S4p2: require("../../assets/IC/A2S4p2.png"),
  A2S8: require("../../assets/IC/A2S8.png"),
  A3S1: require("../../assets/IC/A3S1.png"),
  A3S2: require("../../assets/IC/A3S2.jpg"),
  A3S5: require("../../assets/IC/A3S5.png"),
  A3S8: require("../../assets/IC/A3S8.png"),
  A3S9: require("../../assets/IC/A3S9.jpg"),
  A3S10: require("../../assets/IC/A3S10.jpg"),
  A4S1: require("../../assets/IC/A4S1.png"),
  A4S2: require("../../assets/IC/A4S2.jpg"),
  A4S6: require("../../assets/IC/A4S6.png"),
  A4S6p2: require("../../assets/IC/A4S6p2.png"),
  A4S8: require("../../assets/IC/A4S8.png"),
  A5S1: require("../../assets/IC/A5S1.png"),
  A5S2: require("../../assets/IC/A5S2.jpg"),
  A5S5: require("../../assets/IC/A5S5.png"),
  A5S8: require("../../assets/IC/A5S8.jpg"),
  A7S1: require("../../assets/IC/A7S1.png"),
  A7S5: require("../../assets/IC/A7S5.png"),
  A8S1: require("../../assets/IC/A8S1.png"),
  A8S2: require("../../assets/IC/A8S2.png"),
  A8S3: require("../../assets/IC/A8S3.png"),
  A8S4: require("../../assets/IC/A8S4.png"),
  A8S5: require("../../assets/IC/A8S5.jpg"),
  A8S6: require("../../assets/IC/A8S6.jpg"),
  A8S12: require("../../assets/IC/A8S12.png"),
  A9S3: require("../../assets/IC/A9S3.png"),
  A9S9: require("../../assets/IC/A9S9.jpg"),
  A10S1: require("../../assets/IC/A10S1.png"),
  A10S1p2: require("../../assets/IC/A10S1p2.png"),
  A10S2: require("../../assets/IC/A10S2.jpg"),
  A10S3: require("../../assets/IC/A10S3.jpg"),
  A10S4: require("../../assets/IC/A10S4.jpg"),
  A10S5: require("../../assets/IC/A10S5.jpg"),
  A10S9: require("../../assets/IC/A10S9.png"),
  A10S9p2: require("../../assets/IC/A10S9p2.png"),
  A10S10: require("../../assets/IC/A10S10.jpg"),
  A10S12: require("../../assets/IC/A10S12.jpg"),
  A11S1: require("../../assets/IC/A11S1.png"),
  A11S1p2: require("../../assets/IC/A11S1p2.png"),
  A11S3: require("../../assets/IC/A11S3.jpg"),
  A11S10: require("../../assets/IC/A11S10.jpg"),
  A11S11: require("../../assets/IC/A11S11.jpg"),
  A12S1: require("../../assets/IC/A12S1.png"),
  A12S2: require("../../assets/IC/A12S2.jpg"),
  A12S3: require("../../assets/IC/A12S3.jpg"),
  A12S10: require("../../assets/IC/A12S10.jpg"),
  A12S11: require("../../assets/IC/A12S11.jpg"),
  A12S12: require("../../assets/IC/A12S12.jpg"),
  A12S13: require("../../assets/IC/A12S13.jpg"),
  A13S2: require("../../assets/IC/A13S2.jpg"),
  A13S3: require("../../assets/IC/A13S3.jpg"),
  A13S4: require("../../assets/IC/A13S4.jpg"),
  A13S13: require("../../assets/IC/A13S13.jpg"),
  A14S1: require("../../assets/IC/A14S1.png"),
  A14S2: require("../../assets/IC/A14S2.jpg"),
  A14S11: require("../../assets/IC/A14S11.jpg"),
  A14S12: require("../../assets/IC/A14S12.png"),
  A15S1: require("../../assets/IC/A15S1.png"),
  A15S2: require("../../assets/IC/A15S2.jpg"),
  A15S3: require("../../assets/IC/A15S3.jpg"),
  A15S4: require("../../assets/IC/A15S4.jpg"),
  A15S10: require("../../assets/IC/A15S10.jpg"),
  A15S11: require("../../assets/IC/A15S11.jpg"),
  A16S1: require("../../assets/IC/A16S1.png"),
  A16S9: require("../../assets/IC/A16S9.jpg"),
  A18S1: require("../../assets/IC/A18S1.png"),
  A18S1p2: require("../../assets/IC/A18S1p2.png"),
  A18S2: require("../../assets/IC/A18S2.png"),
  A18S4: require("../../assets/IC/A18S4.png"),
  A19S1: require("../../assets/IC/A19S1.png"),
  A19S1p2: require("../../assets/IC/A19S1p2.png"),
  A19S2: require("../../assets/IC/A19S2.jpg"),
  A19S3: require("../../assets/IC/A19S3.jpg"),
  A19S8: require("../../assets/IC/A19S8.jpg"),
  A20S1: require("../../assets/IC/A20S1.png"),
  A20S2: require("../../assets/IC/A20S2.jpg"),
  A20S4: require("../../assets/IC/A20S4.jpg"),
  A20S7: require("../../assets/IC/A20S7.jpg"),
  A20S11: require("../../assets/IC/A20S11.jpg"),
  A21S1: require("../../assets/IC/A21S1.png"),
  A21S2: require("../../assets/IC/A21S2.jpg"),
  A21S3: require("../../assets/IC/A21S3.jpg"),
  A21S5: require("../../assets/IC/A21S5.jpg"),
  A21S7: require("../../assets/IC/A21S7.jpg"),
  A23S1: require("../../assets/IC/A23S1.png"),
  A23S2: require("../../assets/IC/A23S2.jpg"),
  A23S3: require("../../assets/IC/A23S3.jpg"),
  A23S4: require("../../assets/IC/A23S4.jpg"),
  A23S5: require("../../assets/IC/A23S5.jpg"),
  A23S6: require("../../assets/IC/A23S6.jpg"),
};

export const Empresas = {
  logoSantander: require("../../assets/Santander/santander.png"),
};

export const Santander = {
  A1slide1: require("../../assets/Santander/CRM1.png"),
  A1slide2: require("../../assets/Santander/CRM2.png"),
};

export const Images = {
  seta: require("../../assets/seta.png"),
  setaD: require("../../assets/seta D.png"),
  x: require("../../assets/x.png"),
  teacher: require("../../assets/teacher.png"),
  microfone: require("../../assets/microfone.png"),
  tip: require("../../assets/tip.png"),
  ex10: require("../../assets/LinguetoPerfil.png"),
  ex16: require("../../assets/LinguetoRadio.png"),
};
