import { StyleSheet } from "react-native";
import CORES from "../util/cores";

const geral = StyleSheet.create({
  slide: {
    flex: 1,
    justifyContent: "flex-start",
    alignItems: "center",
    backgroundColor: CORES.BACKGROUND,
    paddingTop: 60,
    marginHorizontal: 20,
    marginBottom: 0,
  },
  headerContainer: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    flexDirection: "row",
    alignItems: "center",
    width: "100%",
    backgroundColor: CORES.BACKGROUND,
    zIndex: 10,
  },
  headerButton: {
    width: 32,
    alignItems: "center",
  },
  headerProgress: {
    flex: 1,
    height: 4,
    backgroundColor: CORES.BORDER_LIGHT,
    borderRadius: 2,
    marginHorizontal: 8,
    overflow: "hidden",
  },
  progressBarFill: {
    height: "100%",
    backgroundColor: CORES.PRIMARY,
    borderRadius: 2,
  },
  headerCircleButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: CORES.PRIMARY,
    alignItems: "center",
    justifyContent: "center",
  },
  headerCircleImage: {
    width: "100%",
    height: "100%",
    resizeMode: "contain",
  },
  nextButton: {
    backgroundColor: CORES.SECONDARY,
    width: 180,
    height: 48,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 12,
    marginHorizontal: 4,
  },
  nextButtonText: {
    color: CORES.WHITE_SHORT,
    fontWeight: "700",
  },
  nextLessonButton: {
    backgroundColor: "#0F73FF",
    width: 180,
    height: 48,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  nextLessonButtonText: {
    color: CORES.WHITE_SHORT,
    fontWeight: "700",
    fontSize: 16,
  },
  buttonRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  fastTypePrompt: {
    width: "88%",
    textAlign: "left",
    fontSize: 20,
    color: "#7BA9D6",
    marginBottom: 18,
    fontWeight: "700",
  },
  listenAnswerMediaWrapper: {
    width: "88%",
    marginBottom: 12,
  },
  listenAnswerMediaCard: {
    width: "100%",
    height: 190,
    backgroundColor: CORES.SURFACE_MUTED,
    borderTopLeftRadius: 18,
    borderTopRightRadius: 18,
    overflow: "hidden",
  },
  listenAnswerImage: {
    width: "100%",
    height: "100%",
    resizeMode: "cover",
  },
  listenAnswerAudioButton: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: CORES.PRIMARY,
    width: "100%",
    height: 48,
    borderBottomLeftRadius: 18,
    borderBottomRightRadius: 18,
    paddingHorizontal: 16,
    gap: 12,
  },
  audioIcon: {
    color: CORES.WHITE_SHORT,
    fontSize: 18,
  },
  audioBar: {
    flex: 1,
    height: 6,
    backgroundColor: "rgba(255,255,255,0.3)",
    borderRadius: 3,
    overflow: "hidden",
  },
  audioProgress: {
    height: "100%",
    backgroundColor: CORES.WHITE_SHORT,
    borderRadius: 3,
  },
  feedbackBox: {
    width: "85%",
    borderWidth: 1,
    borderColor: CORES.SUCCESS,
    backgroundColor: CORES.PANEL_SUCCESS,
    borderRadius: 12,
    padding: 14,
    marginTop: 14,
  },
  feedbackBoxCorrect: {
    borderColor: CORES.SUCCESS,
    backgroundColor: CORES.PANEL_SUCCESS,
  },
  feedbackTitle: {
    color: CORES.SUCCESS_TEXT,
    fontWeight: "700",
    marginBottom: 4,
  },
  feedbackTitleCorrect: {
    color: CORES.SUCCESS_TEXT,
  },
  feedbackTextBlack: {
    color: "#000",
    fontSize: 14,
  },
  successAlertOverlay: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: "flex-end",
    zIndex: 200,
    elevation: 30,
  },
  successAlertCard: {
    backgroundColor: CORES.WHITE,
    borderTopLeftRadius: 22,
    borderTopRightRadius: 22,
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 22,
    borderWidth: 1,
    borderColor: CORES.BORDER_LIGHT,
  },
  successHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 10,
  },
  successIconWrap: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: CORES.SUCCESS_BG,
    alignItems: "center",
    justifyContent: "center",
  },
  successIcon: {
    color: CORES.SUCCESS_TEXT,
    fontSize: 16,
    fontWeight: "700",
  },
  successAlertTitle: {
    color: CORES.SUCCESS_DARK,
    fontSize: 18,
    fontWeight: "800",
  },
  alertFeedbackBox: {
    width: "100%",
    marginTop: 12,
    marginBottom: 8,
  },
  alertContinueButton: {
    width: "100%",
    height: 50,
    borderRadius: 14,
    backgroundColor: CORES.SECONDARY,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 0,
  },
  alertContinueButtonText: {
    color: CORES.WHITE_SHORT,
    fontSize: 18,
    fontWeight: "700",
  },
});

export default geral;
