import { BussinesImages } from "../../../util/images";

export const BUSSINES_STORAGE_KEY = "@curso_progress_v1";

export const bussinesModules = [
  "Introdução ao inglês para negócios",
  "Cumprimentos e Small Talk",
  "Apresentando a empresa",
  "Vocabulário de escritório",
  "E-mails profissionais",
  "Reuniões e agendas",
  "Business presentation",
  "Pedindo e dando informações",
  "Feedback and Review",
  "Telefonemas",
  "Apresentações curtas",
  "Problemas e soluções",
];

export const bussinesSampleLessons = [
  //modulo 1
  {
    module: 0,
    id: "l1",
    title: "Apresentar-se",
    type: "Aula",
    screen: "IntroBusinessEnglish",
    avatar: BussinesImages.aula1,
  },
  {
    module: 0,
    id: "l2",
    title: "Escreva seu email",
    type: "Aula",
    screen: "ProfessionalEmails",
    avatar: BussinesImages.email,
  },
  {
    module: 0,
    id: "l3",
    title: "Continuação: Escreva seu email",
    type: "Prática Oral",
    screen: "ProfessionalEmailsPart2",
    avatar: BussinesImages.email2,
  },
  {
    module: 0,
    id: "l4",
    title: "Quem é?",
    type: "IA",
    screen: "TelephoneConversations",
    avatar: BussinesImages.call,
  },
  {
    module: 0,
    id: "l5",
    title: "Marcando reuniões ",
    type: "IA",
    screen: "MeetingsQuiz",
    avatar: BussinesImages.agenda,
  },
  {
    module: 0,
    id: "l6",
    title: "Networking",
    type: "IA",
    screen: "NetworkingSmallTalk",
    avatar: BussinesImages.storm,
  },
  {
    module: 0,
    id: "l7",
    title: "Shall we start?",
    type: "IA",
    screen: "PracticeMeetingExpressions",
    avatar: BussinesImages.tradutor,
  },
  {
    module: 0,
    id: "l8",
    title: "Meetings",
    type: "IA",
    screen: "MeetingPhrasebook",
    avatar: BussinesImages.reuniao,
  },
  //modulo 2
  {
    module: 1,
    id: "l9",
    title: "What’s up?",
    type: "",
    screen: "",
    avatar: BussinesImages.hi2,
  },
  {
    module: 1,
    id: "20",
    title: "Cumprimentos",
    type: "",
    screen: "",
    avatar: BussinesImages.hi,
  },
  {
    module: 1,
    id: "21",
    title: "Q&A",
    type: "",
    screen: "",
    avatar: BussinesImages.conversa,
  },
  {
    module: 1,
    id: "22",
    title: "Diálogo no elevador",
    type: "",
    screen: "",
    avatar: BussinesImages.conversa2,
  },
  //modulo 3
  {
    module: 2,
    id: "23",
    title: "Trabalho na...",
    type: "",
    screen: "",
    avatar: BussinesImages.company,
  },
  {
    module: 2,
    id: "24",
    title: "Networking",
    type: "",
    screen: "",
    avatar: BussinesImages.storm,
  },
  {
    module: 2,
    id: "25",
    title: "Quem sou eu?",
    type: "",
    screen: "",
    avatar: BussinesImages.who,
  },
  {
    module: 2,
    id: "26",
    title: "Small talk",
    type: "",
    screen: "",
    avatar: BussinesImages.conversa2,
  },
  {
    module: 2,
    id: "27",
    title: "Contra o tempo",
    type: "",
    screen: "",
    avatar: BussinesImages.relogio,
  },
  //modulo 4
  {
    module: 3,
    id: "28",
    title: "introdução office",
    type: "",
    screen: "",
    avatar: BussinesImages.trabalho,
  },
  {
    module: 3,
    id: "29",
    title: "Objetos de escritório",
    type: "",
    screen: "",
    avatar: BussinesImages.material,
  },
  {
    module: 3,
    id: "30",
    title: "Complete a frase",
    type: "",
    screen: "",
    avatar: BussinesImages.celebro,
  },
  {
    module: 3,
    id: "31",
    title: "Situações de escritório",
    type: "",
    screen: "",
    avatar: BussinesImages.secretaria,
  },
  //modulo 5
  {
    module: 4,
    id: "32",
    title: "Formal email",
    type: "",
    screen: "",
    avatar: BussinesImages.envelope,
  },
  {
    module: 4,
    id: "33",
    title: "Como montar o email",
    type: "",
    screen: "",
    avatar: BussinesImages.celebro,
  },
  {
    module: 4,
    id: "34",
    title: "Saudação",
    type: "",
    screen: "",
    avatar: BussinesImages.hi,
  },
  {
    module: 4,
    id: "35",
    title: "Complete o email",
    type: "",
    screen: "",
    avatar: BussinesImages.mensagem,
  },
  {
    module: 4,
    id: "36",
    title: "Rescreva o email",
    type: "",
    screen: "",
    avatar: BussinesImages.secretario,
  },
  {
    module: 4,
    id: "37",
    title: "Situações",
    type: "",
    screen: "",
    avatar: BussinesImages.aula2,
  },
  {
    module: 4,
    id: "38",
    title: "Expressões chaves",
    type: "",
    screen: "",
    avatar: BussinesImages.menino,
  },
  {
    module: 4,
    id: "39",
    title: "Pedido formal",
    type: "",
    screen: "",
    avatar: BussinesImages.lupa,
  },
  {
    module: 4,
    id: "40",
    title: "Escolha a resposta",
    type: "",
    screen: "",
    avatar: BussinesImages.menino2,
  },
  {
    module: 4,
    id: "41",
    title: "Agradecimento",
    type: "",
    screen: "",
    avatar: BussinesImages.obrigado,
  },
  {
    module: 4,
    id: "42",
    title: "Escreva seu email",
    type: "",
    screen: "",
    avatar: BussinesImages.menina,
  },
  {
    module: 4,
    id: "43",
    title: "Confirme info",
    type: "",
    screen: "",
    avatar: BussinesImages.menina2,
  },
  {
    module: 4,
    id: "44",
    title: "I’m sorry",
    type: "",
    screen: "",
    avatar: BussinesImages.sorry,
  },
  {
    module: 4,
    id: "45",
    title: "Soluções",
    type: "",
    screen: "",
    avatar: BussinesImages.ideia,
  },
  {
    module: 4,
    id: "46",
    title: "Escrita errada",
    type: "",
    screen: "",
    avatar: BussinesImages.confuso,
  },
  {
    module: 4,
    id: "47",
    title: "Responda",
    type: "",
    screen: "",
    avatar: BussinesImages.mensagem2,
  },
  //modulo 6
  {
    module: 5,
    id: "48",
    title: "Vocabulário",
    type: "",
    screen: "",
    avatar: BussinesImages.livro,
  },
  {
    module: 5,
    id: "49",
    title: "Marcando reunião",
    type: "",
    screen: "",
    avatar: BussinesImages.agenda2,
  },
  {
    module: 5,
    id: "50",
    title: "Confirmando agenda",
    type: "",
    screen: "",
    avatar: BussinesImages.arquivo,
  },
  {
    module: 5,
    id: "51",
    title: "Minuta",
    type: "",
    screen: "",
    avatar: BussinesImages.texto,
  },
  {
    module: 5,
    id: "52",
    title: "Email de agenda",
    type: "",
    screen: "",
    avatar: BussinesImages.carta,
  },
  {
    module: 5,
    id: "53",
    title: "Listen",
    type: "",
    screen: "",
    avatar: BussinesImages.fone,
  },
  {
    module: 5,
    id: "54",
    title: "Expressões chaves",
    type: "",
    screen: "",
    avatar: BussinesImages.lupa2,
  },
  {
    module: 5,
    id: "55",
    title: "listen and complete",
    type: "",
    screen: "",
    avatar: BussinesImages.fone,
  },
  //modulo 7
  {
    module: 6,
    id: "56",
    title: "Apresentando ideias",
    type: "",
    screen: "",
    avatar: BussinesImages.aula3,
  },
  {
    module: 6,
    id: "57",
    title: "Coloque em ordem",
    type: "",
    screen: "",
    avatar: BussinesImages.aula4,
  },
  {
    module: 6,
    id: "58",
    title: "Complete as transições",
    type: "",
    screen: "",
    avatar: BussinesImages.celebro,
  },
  {
    module: 6,
    id: "59",
    title: "informal/formal",
    type: "",
    screen: "",
    avatar: BussinesImages.secretaria,
  },
  {
    module: 6,
    id: "60",
    title: "O que dizer?",
    type: "",
    screen: "",
    avatar: BussinesImages.what,
  },
  //modulo 8
  {
    module: 7,
    id: "61",
    title: "Could you ....?",
    type: "",
    screen: "",
    avatar: BussinesImages.confuso2,
  },
  {
    module: 7,
    id: "62",
    title: "Complete",
    type: "",
    screen: "",
    avatar: BussinesImages.arquivo,
  },
  {
    module: 7,
    id: "63",
    title: "Review",
    type: "",
    screen: "",
    avatar: BussinesImages.recap,
  },
  //modulo 9
  {
    module: 8,
    id: "64",
    title: "Good, but...",
    type: "",
    screen: "",
    avatar: BussinesImages.estrela,
  },
  {
    module: 8,
    id: "65",
    title: "Complete",
    type: "",
    screen: "",
    avatar: BussinesImages.fone,
  },
  //modulo 10
  {
    module: 9,
    id: "66",
    title: "Phone conversation",
    type: "",
    screen: "",
    avatar: BussinesImages.ligacao,
  },
  {
    module: 9,
    id: "67",
    title: "Listen",
    type: "",
    screen: "",
    avatar: BussinesImages.fone,
  },
  {
    module: 9,
    id: "68",
    title: "Pronunciation",
    type: "",
    screen: "",
    avatar: BussinesImages.tradutor2,
  },
  {
    module: 9,
    id: "69",
    title: "Call practice",
    type: "",
    screen: "",
    avatar: BussinesImages.telefone,
  },
  //modulo 11
  {
    module: 10,
    id: "70",
    title: "Listen",
    type: "",
    screen: "",
    avatar: BussinesImages.fone,
  },
  {
    module: 10,
    id: "71",
    title: "Vocabulário",
    type: "",
    screen: "",
    avatar: BussinesImages.livro,
  },
  {
    module: 10,
    id: "72",
    title: "Call practice",
    type: "",
    screen: "",
    avatar: BussinesImages.meninolivro,
  },
  {
    module: 10,
    id: "73",
    title: "Dialogue",
    type: "",
    screen: "",
    avatar: BussinesImages.conversa2,
  },
  //modulo 12
  {
    module: 11,
    id: "74",
    title: "Identificando problemas",
    type: "",
    screen: "",
    avatar: BussinesImages.config,
  },
  {
    module: 11,
    id: "75",
    title: "Explicando",
    type: "",
    screen: "",
    avatar: BussinesImages.aula5,
  },
  {
    module: 11,
    id: "76",
    title: "Sugerir soluções",
    type: "",
    screen: "",
    avatar: BussinesImages.ideia2,
  },
  {
    module: 11,
    id: "77",
    title: "Tomando decisões",
    type: "",
    screen: "",
    avatar: BussinesImages.diresao,
  },
];
