import createA2LessonScreen from "./A2LessonScreen";
import { ICA2, Images } from "../../../../util/images";

const LESSON_SLIDES = [
  {
    key: "a2ic36s1",
    component: "Exercise17",
    activity: {
      label: "MÓDULO 4 • AULA 36",
      content: [
        "/blue{It's hotter today!}",
        "/blue{Regra Geral: o sufixo -ER}",
        "Quando o adjetivo é curto, geralmente grudamos -ER no final dele para comparar.",
        "Fórmula: adjetivo + ER + THAN.",
      ],
      continueLabel: "Continuar",
    },
  },
  {
    key: "a2ic36s2",
    component: "Exercise14",
    needsSpeech: true,
    activity: {
      prompt: "Escute e escolha.",
      image: ICA2.A36S2,
      audioSource: require("../../../../../mp3/IC/A2/A36S2.mp3"),
      options: ["Tall", "Taller"],
      correctAnswer: "Taller",
      correctOption: "Taller",
      feedbackMessage: "Tall vira taller.",
      successTitle: "Correto",
    },
  },
  {
    key: "a2ic36s3",
    component: "Exercise14",
    needsSpeech: true,
    activity: {
      prompt: "Escute e escolha.",
      image: ICA2.A36S3,
      audioSource: require("../../../../../mp3/IC/A2/A36S3.mp3"),
      options: ["Fast", "Faster"],
      correctAnswer: "Faster",
      correctOption: "Faster",
      feedbackMessage: "Fast vira faster.",
      successTitle: "Correto",
    },
  },
  {
    key: "a2ic36s4",
    component: "Exercise14",
    needsSpeech: true,
    activity: {
      prompt: "Escute e escolha.",
      image: ICA2.A36S4,
      audioSource: require("../../../../../mp3/IC/A2/A36S4.mp3"),
      options: ["Old", "Older"],
      correctAnswer: "Older",
      correctOption: "Older",
      feedbackMessage: "Old vira older.",
      successTitle: "Correto",
    },
  },
  {
    key: "a2ic36s5",
    component: "Exercise13",
    needsSpeech: true,
    activity: {
      prompt: 'O Camaleão correu muito! Escreva "mais rápido".',
      audioSource: require("../../../../../mp3/IC/A2/A36S5.mp3"),
      letters: ["F", "A", "S", "T", "E", "R"],
      correctWord: "FASTER",
      successTitle: "Correto",
      successMessage: "Faster.",
    },
  },
  {
    key: "a2ic36s6",
    component: "Exercise6",
    activity: {
      prompt: "Organize as peças.",
      words: ["The car", "is", "faster", "than", "the bike", "."],
      correctOrder: ["The car", "is", "faster", "than", "the bike", "."],
      successTitle: "Correto",
      successMessage: "The car is faster than the bike.",
    },
  },
  {
    key: "a2ic36s7",
    component: "Exercise5",
    activity: {
      prompt: 'Use a forma certa de "tall".',
      image: ICA2.A36S7,
      sentenceStart: "My brother is",
      sentenceEnd: "than me.",
      options: ["taller", "tallest"],
      correctAnswer: "taller",
      successTitle: "Correto",
      successMessage: "Taller é comparativo; tallest é superlativo.",
    },
  },
  {
    key: "a2ic36s8",
    component: "Exercise17",
    activity: {
      label: "Vocabulário",
      content: [
        "/blue{+10 para seu Vocabulário!}",
        "Long → Longer",
        "Short → Shorter",
        "Young → Younger",
        "Cold → Colder",
        "Clean → Cleaner",
        "Dark → Darker",
        "Hard → Harder",
        "Near → Nearer",
        "Rich → Richer",
        "Cheap → Cheaper",
      ],
      continueLabel: "Continuar",
    },
  },
  {
    key: "a2ic36s9",
    component: "Exercise17",
    activity: {
      label: "Tip",
      content: [
        "/blue{Tchau, Y!}",
        "Se o adjetivo termina em consoante + Y, jogamos o Y fora e colocamos -IER.",
        "Happy → Happier",
      ],
      continueLabel: "Continuar",
    },
  },
  {
    key: "a2ic36s10",
    component: "Exercise14",
    needsSpeech: true,
    activity: {
      prompt: "Escute e escolha.",
      image: ICA2.A36S10,
      audioSource: require("../../../../../mp3/IC/A2/A36S10.mp3"),
      options: ["Happy", "Happier"],
      correctAnswer: "Happier",
      correctOption: "Happier",
      feedbackMessage: "Happy vira happier.",
      successTitle: "Correto",
    },
  },
  {
    key: "a2ic36s11",
    component: "Exercise14",
    needsSpeech: true,
    activity: {
      prompt: "Escute e escolha.",
      image: ICA2.A36S11,
      audioSource: require("../../../../../mp3/IC/A2/A36S11.mp3"),
      options: ["Easy", "Easier"],
      correctAnswer: "Easier",
      correctOption: "Easier",
      feedbackMessage: "Easy vira easier.",
      successTitle: "Correto",
    },
  },
  {
    key: "a2ic36s12",
    component: "Exercise14",
    needsSpeech: true,
    activity: {
      prompt: "Escute e escolha.",
      image: ICA2.A36S12,
      audioSource: require("../../../../../mp3/IC/A2/A36S12.mp3"),
      options: ["Prettie", "Prettier"],
      correctAnswer: "Prettier",
      correctOption: "Prettier",
      feedbackMessage: "Pretty vira prettier.",
      successTitle: "Correto",
    },
  },
  {
    key: "a2ic36s13",
    component: "Exercise13",
    needsSpeech: true,
    activity: {
      prompt: 'Escreva "mais fácil".',
      audioSource: require("../../../../../mp3/IC/A2/A36S13.mp3"),
      letters: ["E", "A", "S", "I", "E", "R"],
      correctWord: "EASIER",
      successTitle: "Correto",
      successMessage: "Easier.",
    },
  },
  {
    key: "a2ic36s14",
    component: "Exercise5",
    activity: {
      prompt: 'Use "happy" corretamente.',
      image: ICA2.A36S14,
      sentenceStart: "I am",
      sentenceEnd: "today than yesterday.",
      options: ["happier", "more happy"],
      correctAnswer: "happier",
      successTitle: "Correto",
      successMessage: "Happy vira happier.",
    },
  },
  {
    key: "a2ic36s15",
    component: "Exercise6",
    activity: {
      prompt: "Organize a frase.",
      words: ["English", "is", "easier", "than", "Chinese", "."],
      correctOrder: ["English", "is", "easier", "than", "Chinese", "."],
      successTitle: "Correto",
      successMessage: "English is easier than Chinese.",
    },
  },
  {
    key: "a2ic36s16",
    component: "Exercise17",
    activity: {
      label: "Vocabulário",
      content: [
        "/blue{+10 Adjetivos com Y}",
        "Funny → Funnier",
        "Heavy → Heavier",
        "Lucky → Luckier",
        "Dirty → Dirtier",
        "Busy → Busier",
        "Early → Earlier",
        "Healthy → Healthier",
        "Hungry → Hungrier",
        "Lazy → Lazier",
        "Noisy → Noisier",
      ],
      continueLabel: "Continuar",
    },
  },
  {
    key: "a2ic36s17",
    component: "Exercise17",
    activity: {
      label: "Tip",
      content: [
        "/blue{O Sanduíche CVC}",
        "Se a palavra termina em consoante + vogal + consoante, dobramos a última letra.",
        "Big → Bigger",
      ],
      continueLabel: "Continuar",
    },
  },
  {
    key: "a2ic36s18",
    component: "Exercise14",
    needsSpeech: true,
    activity: {
      prompt: "Escute e escolha.",
      image: ICA2.A36S18,
      audioSource: require("../../../../../mp3/IC/A2/A36S18.mp3"),
      options: ["Biger", "Bigger"],
      correctAnswer: "Bigger",
      correctOption: "Bigger",
      feedbackMessage: "Big vira bigger, com G dobrado.",
      successTitle: "Correto",
    },
  },
  {
    key: "a2ic36s19",
    component: "Exercise14",
    needsSpeech: true,
    activity: {
      prompt: "Escute e escolha.",
      image: ICA2.A36S19,
      audioSource: require("../../../../../mp3/IC/A2/A36S19.mp3"),
      options: ["Hoter", "Hotter"],
      correctAnswer: "Hotter",
      correctOption: "Hotter",
      feedbackMessage: "Hot vira hotter, com T dobrado.",
      successTitle: "Correto",
    },
  },
  {
    key: "a2ic36s20",
    component: "Exercise14",
    needsSpeech: true,
    activity: {
      prompt: "Escute e escolha.",
      image: ICA2.A36S20,
      audioSource: require("../../../../../mp3/IC/A2/A36S20.mp3"),
      options: ["Thiner", "Thinner"],
      correctAnswer: "Thinner",
      correctOption: "Thinner",
      feedbackMessage: "Thin vira thinner, com N dobrado.",
      successTitle: "Correto",
    },
  },
  {
    key: "a2ic36s21",
    component: "Exercise13",
    needsSpeech: true,
    activity: {
      prompt: 'Escreva "maior", cuidado com a letra dobrada.',
      audioSource: require("../../../../../mp3/IC/A2/A36S21.mp3"),
      letters: ["B", "I", "G", "G", "E", "R"],
      correctWord: "BIGGER",
      successTitle: "Correto",
      successMessage: "Bigger.",
    },
  },
  {
    key: "a2ic36s22",
    component: "Exercise5",
    activity: {
      prompt: 'O verão chegou! Use "hot".',
      image: ICA2.A36S22,
      sentenceStart: "Summer is",
      sentenceEnd: "than winter.",
      options: ["colder", "hotter"],
      correctAnswer: "hotter",
      successTitle: "Correto",
      successMessage: "Hot vira hotter.",
    },
  },
  {
    key: "a2ic36s23",
    component: "Exercise6",
    activity: {
      prompt: "Compare o elefante e o gato.",
      words: ["The elephant", "is", "bigger", "than", "the cat", "."],
      correctOrder: ["The elephant", "is", "bigger", "than", "the cat", "."],
      successTitle: "Correto",
      successMessage: "The elephant is bigger than the cat.",
    },
  },
  {
    key: "a2ic36s24",
    component: "Exercise17",
    activity: {
      label: "Vocabulário",
      content: [
        "/blue{+10 Exemplos de Dobra CVC}",
        "Sad → Sadder",
        "Fat → Fatter",
        "Mad → Madder",
        "Wet → Wetter",
        "Slim → Slimmer",
        "Fit → Fitter",
        "Flat → Flatter",
        "Glad → Gladder",
        "Dim → Dimmer",
        "Grim → Grimmer",
      ],
      continueLabel: "Continuar",
    },
  },
  {
    key: "a2ic36s25",
    component: "Exercise16",
    activity: {
      prompt: "Gravação de áudio",
      image: Images.ex16,
      tipButtonLabel: "Tip",
      instruction: "Grave uma frase comparando duas coisas.",
      helperText: 'Exemplo: "My dog is bigger than my cat."',
      successTitle: "Muito bem!",
      successMessage: "Seu áudio foi gravado.",
    },
  },
  {
    key: "a2ic36s26",
    component: "Exercise17",
    activity: {
      label: "Final",
      content: [
        "/blue{Você é um mestre da comparação!}",
        "Três regras dominadas! Agora você sabe lidar com qualquer adjetivo curto no comparativo.",
      ],
      continueLabel: "Concluir",
    },
  },
];

export default createA2LessonScreen(LESSON_SLIDES);
