import createA2LessonScreen from "./A2LessonScreen";
import { ICA2 } from "../../../../util/images";

const BLOG_TEXT =
  "Hello, everyone! This is my life right now. I’m sitting in my home office. I’m drinking a delicious hot coffee in my favorite mug. Outside, the sun is shining, but I’m working hard on my new project. My cat, Luna, is sleeping on the rug near my feet. Leo is in the kitchen; he’s making a chocolate cake for us! My parents are staying at a hotel near the beach this week. They’re relaxing and walking on the sand. I’m wearing my comfortable blue sweater because the AC is on. I’m feeling very happy and productive today!";

const LESSON_SLIDES = [
  {
    key: "a2ic04s1",
    component: "Exercise17",
    activity: {
      label: "MÓDULO 1 • AULA 4",
      content: [
        "/blue{Sabrina’s Blog}",
        "",
        "Imagine que você está navegando nas redes sociais e para no status de um amigo. Ler em inglês é como montar um quebra-cabeça de ações.",
        "",
        "/blue{Tip - Escaneando a Ação}",
        "Procure primeiro pelos verbos de ajuda: am, is, are.",
        'Palavras como "right now", "at the moment" e "look!" confirmam que a cena está acontecendo agora.',
      ],
      continueLabel: "Continuar",
    },
  },
  {
    key: "a2ic04s2",
    type: "listenOnly",
    activity: {
      prompt: "Ouça o blog da Sabrina",
      image: ICA2.A4S2,
      transcript: BLOG_TEXT,
      audioText: BLOG_TEXT,
      continueLabel: "Continuar",
    },
  },
  {
    key: "a2ic04s3",
    component: "Exercise5",
    activity: {
      prompt: "Onde a Sabrina está trabalhando?",
      image: ICA2.A4S2,
      sentenceStart: "Sabrina is working in her",
      sentenceEnd: ".",
      options: ["home office", "kitchen"],
      correctAnswer: "home office",
      successTitle: "Correto",
      successMessage: "Ela está trabalhando no home office.",
    },
  },
  {
    key: "a2ic04s4",
    component: "Exercise5",
    activity: {
      prompt: "O que ela está bebendo?",
      image: ICA2.A1S5,
      sentenceStart: "She is drinking",
      sentenceEnd: "coffee.",
      options: ["hot", "cold"],
      correctAnswer: "hot",
      successTitle: "Correto",
      successMessage: "She is drinking hot coffee.",
    },
  },
  {
    key: "a2ic04s5",
    component: "Exercise5",
    activity: {
      prompt: "O que o sol está fazendo lá fora?",
      image: ICA2.A4S13,
      sentenceStart: "The sun is",
      sentenceEnd: ".",
      options: ["shining", "raining"],
      correctAnswer: "shining",
      successTitle: "Correto",
      successMessage: "The sun is shining.",
    },
  },
  {
    key: "a2ic04s6",
    component: "Exercise5",
    activity: {
      prompt: "Onde a gata Luna está dormindo?",
      image: ICA2.A4S2,
      sentenceStart: "Luna is sleeping on the",
      sentenceEnd: ".",
      options: ["rug", "table"],
      correctAnswer: "rug",
      successTitle: "Correto",
      successMessage: "Luna is sleeping on the rug.",
    },
  },
  {
    key: "a2ic04s7",
    component: "Exercise5",
    activity: {
      prompt: "O que o Leo está fazendo na cozinha?",
      image: ICA2.A1S8,
      sentenceStart: "He’s",
      sentenceEnd: "a cake.",
      options: ["making", "doing"],
      correctAnswer: "making",
      successTitle: "Correto",
      successMessage: "He’s making a cake.",
    },
  },
  {
    key: "a2ic04s8",
    component: "Exercise5",
    activity: {
      prompt: "Onde os pais da Sabrina estão passando a semana?",
      image: ICA2.A4S13,
      sentenceStart: "They are staying at a",
      sentenceEnd: ".",
      options: ["hotel", "park"],
      correctAnswer: "hotel",
      successTitle: "Correto",
      successMessage: "They are staying at a hotel.",
    },
  },
  {
    key: "a2ic04s9",
    component: "Exercise5",
    activity: {
      prompt: "O que os pais dela estão fazendo na praia?",
      image: ICA2.A4S13,
      sentenceStart: "They are",
      sentenceEnd: "and walking.",
      options: ["relaxing", "working"],
      correctAnswer: "relaxing",
      successTitle: "Correto",
      successMessage: "They are relaxing and walking.",
    },
  },
  {
    key: "a2ic04s10",
    component: "Exercise5",
    activity: {
      prompt: "Por que a Sabrina está usando um casaco?",
      image: ICA2.A4S2,
      sentenceStart: "Because the",
      sentenceEnd: "is on.",
      options: ["AC", "oven"],
      correctAnswer: "AC",
      successTitle: "Correto",
      successMessage: "Because the AC is on.",
    },
  },
  {
    key: "a2ic04s11",
    component: "Exercise5",
    activity: {
      prompt: "Qual é a cor do casaco da Sabrina?",
      image: ICA2.A4S2,
      sentenceStart: "She is wearing a",
      sentenceEnd: "sweater.",
      options: ["blue", "red"],
      correctAnswer: "blue",
      successTitle: "Correto",
      successMessage: "She is wearing a blue sweater.",
    },
  },
  {
    key: "a2ic04s12",
    component: "Exercise5",
    activity: {
      prompt: "Como a Sabrina está se sentindo hoje?",
      image: ICA2.A4S2,
      sentenceStart: "She is feeling",
      sentenceEnd: "and productive.",
      options: ["happy", "tired"],
      correctAnswer: "happy",
      successTitle: "Correto",
      successMessage: "She is feeling happy and productive.",
    },
  },
  {
    key: "a2ic04s13",
    component: "Exercise3",
    needsSpeech: true,
    activity: {
      prompt: "Segundo o texto, verdadeiro ou falso?",
      image: ICA2.A4S13,
      audioText: "Sabrina is working in her home office.",
      statement:
        "Segundo o texto, a Sabrina está de férias na praia com os pais dela.",
      textOnScreen: "A Sabrina está de férias na praia com os pais dela.",
      options: ["true", "false"],
      correctAnswer: "false",
      successTitle: "Correto",
      successMessage:
        "False. Ela está trabalhando no escritório; os pais estão na praia.",
      feedbackMessage: "No texto, Sabrina está no home office.",
    },
  },
  {
    key: "a2ic04s14",
    component: "Exercise6",
    activity: {
      prompt: "Monte a frase que descreve o que o Leo está fazendo:",
      words: ["is", "making", "Leo", "cake.", "a", "chocolate"],
      correctOrder: ["Leo", "is", "making", "a", "chocolate", "cake."],
      successTitle: "Correto",
      successMessage: "Leo is making a chocolate cake.",
    },
  },
  {
    key: "a2ic04s15",
    component: "Exercise11",
    activity: {
      prompt: "Digite estes verbos do texto com -ING:",
      title: "Escreva a forma com -ING",
      placeholder: "Digite aqui",
      secondsPerWord: 8,
      words: ["Shining", "Sitting", "Making", "Feeling", "Staying"],
      successTitle: "Correto",
      successMessage: "Você reconheceu as ações principais do texto.",
    },
  },
];

export default createA2LessonScreen(LESSON_SLIDES);
