import createA2LessonScreen from "./A2LessonScreen";
import { ICA2, Images } from "../../../../util/images";

const LESSON_SLIDES = [
  {
    key: "a2ic35s1",
    component: "Exercise17",
    activity: {
      label: "MÓDULO 4 • AULA 35",
      content: [
        "/blue{It's more beautiful!}",
        "/blue{Comparando com Estilo!}",
        'Usamos o comparativo para mostrar que algo "ganha" de outra coisa em alguma característica.',
        "Quando o adjetivo é longo, a regra é simples: MORE + adjetivo + THAN.",
        'Exemplo: "A Ferrari is more expensive than a bicycle."',
      ],
      continueLabel: "Continuar",
    },
  },
  {
    key: "a2ic35s2",
    component: "Exercise14",
    needsSpeech: true,
    activity: {
      prompt: "Escute e escolha.",
      image: ICA2.A35S2,
      audioSource: require("../../../../../mp3/IC/A2/A35S2.mp3"),
      options: ["Beautiful", "Beauty"],
      correctAnswer: "Beautiful",
      correctOption: "Beautiful",
      feedbackMessage: "Beautiful é um adjetivo longo e elegante.",
      successTitle: "Correto",
    },
  },
  {
    key: "a2ic35s3",
    component: "Exercise14",
    needsSpeech: true,
    activity: {
      prompt: "Escute e escolha.",
      image: ICA2.A35S3,
      audioSource: require("../../../../../mp3/IC/A2/A35S3.mp3"),
      options: ["Expansion", "Expensive"],
      correctAnswer: "Expensive",
      correctOption: "Expensive",
      feedbackMessage: "Expensive significa caro.",
      successTitle: "Correto",
    },
  },
  {
    key: "a2ic35s4",
    component: "Exercise14",
    needsSpeech: true,
    activity: {
      prompt: "Escute e escolha.",
      image: ICA2.A35S4,
      audioSource: require("../../../../../mp3/IC/A2/A35S4.mp3"),
      options: ["Comfortable", "Comfort"],
      correctAnswer: "Comfortable",
      correctOption: "Comfortable",
      feedbackMessage: "Comfortable significa confortável.",
      successTitle: "Correto",
    },
  },
  {
    key: "a2ic35s5",
    component: "Exercise14",
    needsSpeech: true,
    activity: {
      prompt: "Escute e escolha.",
      image: ICA2.A35S5,
      audioSource: require("../../../../../mp3/IC/A2/A35S5.mp3"),
      options: ["Interesting", "Interest"],
      correctAnswer: "Interesting",
      correctOption: "Interesting",
      feedbackMessage: "Interesting é perfeito para comparar livros e filmes.",
      successTitle: "Correto",
    },
  },
  {
    key: "a2ic35s6",
    component: "Exercise18",
    activity: {
      prompt: 'Digite: "Este relógio é mais caro do que aquele."',
      scrambledWords: [
        "expensive",
        "than",
        "is",
        "more",
        "This",
        "watch",
        "that",
        "one",
        ".",
      ],
      correctAnswer: "This watch is more expensive than that one.",
      successTitle: "Correto",
      successMessage: "This watch is more expensive than that one.",
    },
  },
  {
    key: "a2ic35s7",
    component: "Exercise18",
    activity: {
      prompt: 'Digite: "O sofá é mais confortável que a cadeira."',
      scrambledWords: [
        "sofa",
        "more",
        "comfortable",
        "than",
        "is",
        "chair",
        "The",
        ".",
      ],
      correctAnswer: "The sofa is more comfortable than the chair.",
      successTitle: "Correto",
      successMessage: "The sofa is more comfortable than the chair.",
    },
  },
  {
    key: "a2ic35s8",
    component: "Exercise18",
    activity: {
      prompt: 'Digite: "Paris é mais bonita que Londres."',
      scrambledWords: [
        "Paris",
        "more",
        "than",
        "is",
        "beautiful",
        "London",
        ".",
      ],
      correctAnswer: "Paris is more beautiful than London.",
      successTitle: "Correto",
      successMessage: "Paris is more beautiful than London.",
    },
  },
  {
    key: "a2ic35s9",
    component: "Exercise4",
    activity: {
      prompt:
        'Qual a forma correta de comparar usando o adjetivo "intelligent"?',
      image: ICA2.A35S9,
      wrongSentence: "Choose the correct comparative form.",
      options: [
        "Intelligent than",
        "More intelligent than",
        "Intelligent more than",
      ],
      correctAnswer: "More intelligent than",
      successTitle: "Correto",
      successMessage: "Adjetivo longo usa more + adjective + than.",
    },
  },
  {
    key: "a2ic35s10",
    component: "Exercise8",
    activity: {
      prompt: "In my opinion, the book is...",
      image: ICA2.A35S10,
      options: [
        "more interesting than the TV.",
        "interesting more than the TV.",
      ],
      correctAnswer: "more interesting than the TV.",
      successTitle: "Correto",
      successMessage: "More interesting than é a ordem correta.",
    },
  },
  {
    key: "a2ic35s11",
    component: "Exercise13",
    needsSpeech: true,
    activity: {
      prompt: "Escreva o adjetivo corretamente.",
      audioSource: require("../../../../../mp3/IC/A2/A35S11.mp3"),
      letters: ["B", "E", "A", "U", "T", "I", "F", "U", "L"],
      correctWord: "BEAUTIFUL",
      successTitle: "Correto",
      successMessage: "Beautiful.",
    },
  },
  {
    key: "a2ic35s12",
    component: "Exercise13",
    needsSpeech: true,
    activity: {
      prompt: "Coloque as letras na ordem.",
      audioSource: require("../../../../../mp3/IC/A2/A35S12.mp3"),
      letters: ["E", "X", "P", "E", "N", "S", "I", "V", "E"],
      correctWord: "EXPENSIVE",
      successTitle: "Correto",
      successMessage: "Expensive.",
    },
  },
  {
    key: "a2ic35s13",
    component: "Exercise13",
    needsSpeech: true,
    activity: {
      prompt: "Qual é o adjetivo?",
      audioSource: require("../../../../../mp3/IC/A2/A35S13.mp3"),
      letters: ["C", "O", "M", "F", "O", "R", "T", "A", "B", "L", "E"],
      correctWord: "COMFORTABLE",
      successTitle: "Correto",
      successMessage: "Comfortable.",
    },
  },
  {
    key: "a2ic35s14",
    component: "Exercise19",
    activity: {
      prompt: "Escute e digite com atenção.",
      audioSource: require("../../../../../mp3/IC/A2/A35S14.mp3"),
      correctAnswer: "This movie is more interesting than the book.",
      successTitle: "Correto",
      successMessage: "This movie is more interesting than the book.",
    },
  },
  {
    key: "a2ic35s15",
    component: "Exercise19",
    activity: {
      prompt: "Escute e digite com atenção.",
      audioSource: require("../../../../../mp3/IC/A2/A35S15.mp3"),
      correctAnswer: "Paris is more beautiful than London.",
      successTitle: "Correto",
      successMessage: "Paris is more beautiful than London.",
    },
  },
  {
    key: "a2ic35s16",
    component: "Exercise12",
    activity: {
      prompt: 'Complete com sua opinião: "English is more important than..."',
      instruction: "Escreva uma frase completa.",
      correctAnswer: "English is more important than math.",
      successTitle: "Muito bem!",
      successMessage: "Opinião registrada.",
    },
  },
  {
    key: "a2ic35s17",
    component: "Exercise16",
    activity: {
      prompt: "Gravação de áudio",
      image: Images.ex16,
      tipButtonLabel: "Tip",
      instruction: 'Grave: "My car is more expensive than my bike."',
      helperText: "My car is more expensive than my bike.",
      successTitle: "Muito bem!",
      successMessage: "Seu áudio foi gravado.",
    },
  },
  {
    key: "a2ic35s18",
    component: "Exercise17",
    activity: {
      label: "Final",
      content: [
        "/blue{Nível 1 Concluído!}",
        "Você dominou os adjetivos longos e até a escrita deles. No próximo encontro, vamos para os adjetivos curtinhos.",
      ],
      continueLabel: "Concluir",
    },
  },
];

export default createA2LessonScreen(LESSON_SLIDES);
