import createA2LessonScreen from "./A2LessonScreen";
import { ICA2 } from "../../../../util/images";

const LESSON_SLIDES = [
  {
    key: "a2ic38s1",
    component: "Exercise17",
    activity: {
      label: "MÓDULO 4 • AULA 38",
      content: [
        "/blue{It's much better now!}",
        "/blue{Intensidade Máxima!}",
        "Às vezes, a diferença entre duas coisas é enorme. Para isso, usamos much ou a lot antes do comparativo.",
        "Much faster: muito mais rápido.",
        "A lot more expensive: bem mais caro.",
      ],
      continueLabel: "Continuar",
    },
  },
  {
    key: "a2ic38s2",
    component: "Exercise14",
    needsSpeech: true,
    activity: {
      prompt: "Escute e escolha.",
      image: ICA2.A38S2,
      audioSource: require("../../../../../mp3/IC/A2/A38S2.mp3"),
      options: ["Much better", "Very better"],
      correctAnswer: "Much better",
      correctOption: "Much better",
      feedbackMessage: "Dizemos much better, não very better.",
      successTitle: "Correto",
    },
  },
  {
    key: "a2ic38s3",
    component: "Exercise14",
    needsSpeech: true,
    activity: {
      prompt: "Escute e escolha.",
      image: ICA2.A38S3,
      audioSource: require("../../../../../mp3/IC/A2/A38S3.mp3"),
      options: ["Many faster", "A lot faster"],
      correctAnswer: "A lot faster",
      correctOption: "A lot faster",
      feedbackMessage: "A lot faster significa bem mais rápido.",
      successTitle: "Correto",
    },
  },
  {
    key: "a2ic38s4",
    component: "Exercise14",
    needsSpeech: true,
    activity: {
      prompt: "Escute e escolha.",
      image: ICA2.A38S4,
      audioSource: require("../../../../../mp3/IC/A2/A38S4.mp3"),
      options: ["Such more expensive", "Much more expensive"],
      correctAnswer: "Much more expensive",
      correctOption: "Much more expensive",
      feedbackMessage: "Use much antes de more expensive.",
      successTitle: "Correto",
    },
  },
  {
    key: "a2ic38s5",
    component: "Exercise13",
    needsSpeech: true,
    activity: {
      prompt: 'Escreva a expressão para "muito".',
      audioSource: require("../../../../../mp3/IC/A2/A38S5.mp3"),
      letters: ["A", "L", "O", "T"],
      correctWord: "ALOT",
      successTitle: "Correto",
      successMessage: "A lot.",
    },
  },
  {
    key: "a2ic38s6",
    component: "Exercise6",
    activity: {
      prompt: "Organize a frase com intensidade.",
      words: ["Gold", "is", "a lot", "more expensive", "than", "silver", "."],
      correctOrder: [
        "Gold",
        "is",
        "a lot",
        "more expensive",
        "than",
        "silver",
        ".",
      ],
      successTitle: "Correto",
      successMessage: "Gold is a lot more expensive than silver.",
    },
  },
  {
    key: "a2ic38s7",
    component: "Exercise17",
    activity: {
      label: "Lista",
      content: [
        "/blue{Turbinando a Frase}",
        "Much older: muito mais velho.",
        "A lot bigger: bem maior.",
        "Much more interesting: muito mais interessante.",
        "A lot easier: bem mais fácil.",
      ],
      continueLabel: "Continuar",
    },
  },
  {
    key: "a2ic38s8",
    component: "Exercise17",
    activity: {
      label: "Tip",
      content: [
        "/blue{Pequenas Diferenças}",
        "Se a diferença for pequena, usamos a bit antes do comparativo.",
        'Exemplo: "I am a bit taller than my brother."',
      ],
      continueLabel: "Continuar",
    },
  },
  {
    key: "a2ic38s9",
    component: "Exercise14",
    needsSpeech: true,
    activity: {
      prompt: "Escute e escolha.",
      image: ICA2.A38S9,
      audioSource: require("../../../../../mp3/IC/A2/A38S9.mp3"),
      options: ["Taller", "A bit taller"],
      correctAnswer: "A bit taller",
      correctOption: "A bit taller",
      feedbackMessage: "A bit taller significa um pouco mais alto.",
      successTitle: "Correto",
    },
  },
  {
    key: "a2ic38s10",
    component: "Exercise14",
    needsSpeech: true,
    activity: {
      prompt: "Escute e escolha.",
      image: ICA2.A38S10,
      audioSource: require("../../../../../mp3/IC/A2/A38S10.mp3"),
      options: ["A bit easier", "Easier"],
      correctAnswer: "A bit easier",
      correctOption: "A bit easier",
      feedbackMessage: "A bit easier significa um pouco mais fácil.",
      successTitle: "Correto",
    },
  },
  {
    key: "a2ic38s11",
    component: "Exercise13",
    needsSpeech: true,
    activity: {
      prompt: 'Escreva "um pouco" em inglês.',
      audioSource: require("../../../../../mp3/IC/A2/A38S11.mp3"),
      letters: ["A", "B", "I", "T"],
      correctWord: "ABIT",
      successTitle: "Correto",
      successMessage: "A bit.",
    },
  },
  {
    key: "a2ic38s12",
    component: "Exercise6",
    activity: {
      prompt: "Ordene a comparação leve.",
      words: ["Today", "is", "a bit", "hotter", "than", "yesterday", "."],
      correctOrder: [
        "Today",
        "is",
        "a bit",
        "hotter",
        "than",
        "yesterday",
        ".",
      ],
      successTitle: "Correto",
      successMessage: "Today is a bit hotter than yesterday.",
    },
  },
  {
    key: "a2ic38s13",
    component: "Exercise17",
    activity: {
      label: "Tip",
      content: [
        "/blue{O Caminho Inverso}",
        'Para dizer "menos do que", usamos less antes do adjetivo.',
        "Fórmula: LESS + adjetivo + THAN.",
      ],
      continueLabel: "Continuar",
    },
  },
  {
    key: "a2ic38s14",
    component: "Exercise14",
    needsSpeech: true,
    activity: {
      prompt: "Escute e escolha.",
      image: ICA2.A38S14,
      audioSource: require("../../../../../mp3/IC/A2/A38S14.mp3"),
      options: ["More expensive", "Less expensive"],
      correctAnswer: "Less expensive",
      correctOption: "Less expensive",
      feedbackMessage: "Less expensive significa menos caro.",
      successTitle: "Correto",
    },
  },
  {
    key: "a2ic38s15",
    component: "Exercise14",
    needsSpeech: true,
    activity: {
      prompt: "Escute e escolha.",
      image: ICA2.A38S15,
      audioSource: require("../../../../../mp3/IC/A2/A38S15.mp3"),
      options: ["More interesting", "Less interesting"],
      correctAnswer: "Less interesting",
      correctOption: "Less interesting",
      feedbackMessage: "Less interesting significa menos interessante.",
      successTitle: "Correto",
    },
  },
  {
    key: "a2ic38s16",
    component: "Exercise13",
    needsSpeech: true,
    activity: {
      prompt: 'Escreva "menos" em inglês.',
      audioSource: require("../../../../../mp3/IC/A2/A38S16.mp3"),
      letters: ["L", "E", "S", "S"],
      correctWord: "LESS",
      successTitle: "Correto",
      successMessage: "Less.",
    },
  },
  {
    key: "a2ic38s17",
    component: "Exercise6",
    activity: {
      prompt: "O filme não foi tão bom. Ordene a frase.",
      words: [
        "The movie",
        "was",
        "less",
        "interesting",
        "than",
        "the book",
        ".",
      ],
      correctOrder: [
        "The movie",
        "was",
        "less",
        "interesting",
        "than",
        "the book",
        ".",
      ],
      successTitle: "Correto",
      successMessage: "The movie was less interesting than the book.",
    },
  },
  {
    key: "a2ic38s18",
    component: "Exercise5",
    activity: {
      prompt: "Falando de conforto.",
      image: ICA2.A38S18,
      sentenceStart: "A chair is",
      sentenceEnd: "comfortable than a sofa.",
      options: ["less", "more"],
      correctAnswer: "less",
      successTitle: "Correto",
      successMessage: "A chair is less comfortable than a sofa.",
    },
  },
  {
    key: "a2ic38s19",
    component: "Exercise19",
    activity: {
      prompt: "Escute e digite com atenção.",
      audioSource: require("../../../../../mp3/IC/A2/A38S19.mp3"),
      correctAnswer: "Learning English is much easier than I thought.",
      successTitle: "Correto",
      successMessage: "Learning English is much easier than I thought.",
    },
  },
  {
    key: "a2ic38s20",
    component: "Exercise16",
    activity: {
      prompt: "Gravação de áudio",
      instruction: "Grave uma frase comparando dois hobbies seus.",
      helperText:
        'Exemplo: "Playing guitar is a lot more interesting than watching TV."',
      successTitle: "Muito bem!",
      successMessage: "Seu áudio foi gravado.",
    },
  },
  {
    key: "a2ic38s21",
    component: "Exercise17",
    activity: {
      label: "Final",
      content: [
        "/blue{Mestre dos Detalhes!}",
        "Agora suas comparações não são apenas mais ou menos. Você consegue dar o tom exato da diferença.",
      ],
      continueLabel: "Concluir",
    },
  },
];

export default createA2LessonScreen(LESSON_SLIDES);
