import createA2LessonScreen from "./A2LessonScreen";
import { ICA2, Images } from "../../../../util/images";

const LESSON_SLIDES = [
  {
    key: "a2ic22s1",
    component: "Exercise17",
    activity: {
      label: "MÓDULO 2 • AULA 22",
      content: [
        "/blue{First / Then / Finally}",
        "/blue{A Arte de Contar Histórias}",
        "Para contar uma história, precisamos de ordem. Hoje você vai aprender os sequenciadores.",
      ],
      continueLabel: "Continuar",
    },
  },
  {
    key: "a2ic22s2",
    component: "Exercise14",
    needsSpeech: true,
    activity: {
      prompt: "Vocabulário: escute e escolha.",
      image: ICA2.A22S2,
      audioSource: require("../../../../../mp3/IC/A2/A22S2.mp3"),
      options: ["First", "Fast"],
      correctAnswer: "First",
      correctOption: "First",
      feedbackMessage: "First significa primeiro.",
      successTitle: "Correto",
    },
  },
  {
    key: "a2ic22s3",
    component: "Exercise14",
    needsSpeech: true,
    activity: {
      prompt: "Vocabulário: escute e escolha.",
      image: ICA2.A22S3,
      audioSource: require("../../../../../mp3/IC/A2/A22S3.mp3"),
      options: ["Ten", "Then"],
      correctAnswer: "Then",
      correctOption: "Then",
      feedbackMessage: "Then significa então/depois.",
      successTitle: "Correto",
    },
  },
  {
    key: "a2ic22s4",
    component: "Exercise14",
    needsSpeech: true,
    activity: {
      prompt: "Vocabulário: escute e escolha.",
      image: ICA2.A22S4,
      audioSource: require("../../../../../mp3/IC/A2/A22S4.mp3"),
      options: ["After that", "After this"],
      correctAnswer: "After that",
      correctOption: "After that",
      feedbackMessage: "After that significa depois disso.",
      successTitle: "Correto",
    },
  },
  {
    key: "a2ic22s5",
    component: "Exercise14",
    needsSpeech: true,
    activity: {
      prompt: "Vocabulário: escute e escolha.",
      image: ICA2.A22S4p2,
      audioSource: require("../../../../../mp3/IC/A2/A22S5.mp3"),
      options: ["Final", "Finally"],
      correctAnswer: "Finally",
      correctOption: "Finally",
      feedbackMessage: "Finally significa finalmente/por fim.",
      successTitle: "Correto",
    },
  },
  {
    key: "a2ic22s6",
    component: "Exercise17",
    activity: {
      label: "Tip",
      content: [
        "/blue{O Mapa da História}",
        "First: início",
        "Then / After that: meio",
        "Finally: fim",
      ],
      continueLabel: "Continuar",
    },
  },
  {
    key: "a2ic22s7",
    component: "Exercise18",
    activity: {
      prompt: "Organize o início da história:",
      scrambledSentence: "First / , / I / woke / up / .",
      correctAnswer: "First, I woke up.",
      placeholder: "Digite a frase",
      submitLabel: "Responder",
      successTitle: "Correto",
      successMessage: "First, I woke up.",
    },
  },
  {
    key: "a2ic22s8",
    component: "Exercise18",
    activity: {
      prompt: "Agora o próximo passo:",
      scrambledSentence: "Then / , / I / had / breakfast / .",
      correctAnswer: "Then, I had breakfast.",
      placeholder: "Digite a frase",
      submitLabel: "Responder",
      successTitle: "Correto",
      successMessage: "Then, I had breakfast.",
    },
  },
  {
    key: "a2ic22s9",
    component: "Exercise19",
    needsSpeech: true,
    activity: {
      prompt: "Escute e digite a frase completa:",
      audioSource: require("../../../../../mp3/IC/A2/A22S9.mp3"),
      correctAnswer: "After that, I went to the park.",
      placeholder: "Digite a frase",
      submitLabel: "Responder",
      successTitle: "Correto",
      successMessage: "Você escreveu a frase com sequenciador.",
      errorMessage: "Confira: After that, I went to the park.",
    },
  },
  {
    key: "a2ic22s10",
    component: "Exercise17",
    activity: {
      label: "Part 1",
      content: [
        "/blue{The Morning}",
        "First, I woke up early and exercised. Then, I took a shower and prepared a big breakfast. I was very happy!",
      ],
      continueLabel: "Continuar",
    },
  },
  {
    key: "a2ic22s11",
    component: "Exercise4",
    activity: {
      prompt: "O que a pessoa fez logo depois de acordar?",
      image: ICA2.A22S11,
      wrongSentence: "Choose the correct answer.",
      options: ["Tomou banho.", "Exercitou-se."],
      correctAnswer: "Exercitou-se.",
      successTitle: "Correto",
      successMessage: "First, I woke up early and exercised.",
    },
  },
  {
    key: "a2ic22s12",
    component: "Exercise17",
    activity: {
      label: "Part 2",
      content: [
        "/blue{The Afternoon}",
        "After that, I went to the city center. I met my best friend and we bought some clothes. We didn't have much money, but it was fun!",
      ],
      continueLabel: "Continuar",
    },
  },
  {
    key: "a2ic22s13",
    component: "Exercise4",
    activity: {
      prompt: "Com quem a pessoa se encontrou no centro?",
      image: ICA2.A22S13,
      wrongSentence: "Choose the correct answer.",
      options: ["Com seu melhor amigo.", "Com seu irmão."],
      correctAnswer: "Com seu melhor amigo.",
      successTitle: "Correto",
      successMessage: "I met my best friend.",
    },
  },
  {
    key: "a2ic22s14",
    component: "Exercise17",
    activity: {
      label: "Part 3",
      content: [
        "/blue{The End}",
        "Finally, we went to a restaurant and ate a delicious pizza. At 10 PM, I went home and slept. It was a perfect day!",
      ],
      continueLabel: "Continuar",
    },
  },
  {
    key: "a2ic22s15",
    component: "Exercise19",
    needsSpeech: true,
    activity: {
      prompt: "Escute como a história terminou e digite:",
      audioSource: require("../../../../../mp3/IC/A2/A22S15.mp3"),
      correctAnswer: "Finally, we ate pizza.",
      placeholder: "Digite a frase",
      submitLabel: "Responder",
      successTitle: "Correto",
      successMessage: "Você escreveu o fechamento da história.",
      errorMessage: "Confira: Finally, we ate pizza.",
    },
  },
  {
    key: "a2ic22s16",
    component: "Exercise7",
    activity: {
      prompt: "Coloque as frases na ordem correta.",
      options: [
        "Finally, I went to sleep at 11 PM.",
        "First, I woke up at 7 AM.",
        "After that, I went to work by bus.",
        "Then, I had a big breakfast.",
      ],
      correctOrder: [
        "First, I woke up at 7 AM.",
        "Then, I had a big breakfast.",
        "After that, I went to work by bus.",
        "Finally, I went to sleep at 11 PM.",
      ],
      successTitle: "Correto",
      successMessage:
        "A história ficou em ordem: First, Then, After that, Finally.",
    },
  },
  {
    key: "a2ic22s17",
    component: "Exercise2",
    activity: {
      prompt: "Complete o texto com sequenciadores.",
      paragraphs: [
        [
          "",
          { id: "b1", answer: "First", options: ["First", "Then", "Finally"] },
          ", I saw a movie. ",
          { id: "b2", answer: "Then", options: ["First", "Then", "Finally"] },
          ", I felt hungry and ate a sandwich. ",
          {
            id: "b3",
            answer: "Finally",
            options: ["First", "Then", "Finally"],
          },
          ", I went to bed.",
        ],
      ],
      successTitle: "Correto",
      successMessage: "First, Then e Finally organizam a história.",
    },
  },
  {
    key: "a2ic22s18",
    component: "Exercise18",
    activity: {
      prompt: "Digite a frase na ordem correta:",
      scrambledSentence: "After / that / , / I / visited / Sarah / .",
      correctAnswer: "After that, I visited Sarah.",
      placeholder: "Digite a frase",
      submitLabel: "Responder",
      successTitle: "Correto",
      successMessage: "After that, I visited Sarah.",
    },
  },
  {
    key: "a2ic22s19",
    component: "Exercise19",
    needsSpeech: true,
    activity: {
      prompt: "Escute e digite a frase final da história:",
      audioSource: require("../../../../../mp3/IC/A2/A22S19.mp3"),
      correctAnswer: "Finally, I arrived home.",
      placeholder: "Digite a frase",
      submitLabel: "Responder",
      successTitle: "Correto",
      successMessage: "Você escreveu a frase final.",
      errorMessage: "Confira: Finally, I arrived home.",
    },
  },
  {
    key: "a2ic22s20",
    component: "Exercise12",
    activity: {
      prompt: "Escrita criativa",
      instruction: "Escreva o que você fez no último final de semana.",
      helperText: "Use obrigatoriamente: First, Then, After that e Finally.",
      placeholder: "Digite sua história aqui",
      tipText: "Use Simple Past e sequenciadores.",
      successTitle: "Muito bem!",
      successMessage: "Você organizou sua história com sequenciadores.",
    },
  },
  {
    key: "a2ic22s21",
    component: "Exercise16",
    activity: {
      prompt: "Gravação de áudio",
      image: Images.ex16,
      tipButtonLabel: "Tip",
      instruction:
        "Grave um áudio contando sua rotina de ontem de forma rápida.",
      helperText: 'Exemplo: "First, I drank coffee. Then, I worked..."',
      tipText: "Use First, Then, After that e Finally.",
      successTitle: "Muito bem!",
      successMessage: "Seu áudio foi gravado.",
    },
  },
  {
    key: "a2ic22s22",
    component: "Exercise17",
    activity: {
      label: "Final",
      content: [
        "/blue{Storyteller de Sucesso!}",
        "Você aprendeu a organizar o tempo nas suas histórias. Isso deixa seu inglês mais natural e profissional.",
      ],
      continueLabel: "Concluir",
    },
  },
];

export default createA2LessonScreen(LESSON_SLIDES);
