import createA2LessonScreen from "./A2LessonScreen";
import { ICA2 } from "../../../../util/images";

const LESSON_SLIDES = [
  {
    key: "a2ic07intro",
    component: "Exercise17",
    activity: {
      label: "MÓDULO 1 • AULA 7",
      content: [
        "/blue{Are you writing?}",
        "",
        "A curiosidade é o que faz o aprendizado avançar. Para perguntar, o Verbo BE (am/is/are) pula para a frente do sujeito.",
        "You are reading. → Are you reading?",
      ],
      continueLabel: "Continuar",
    },
  },
  {
    key: "a2ic07s1",
    component: "Exercise6",
    activity: {
      prompt: "Monte a pergunta para descobrir o que Michael está fazendo:",
      words: ["is", "What", "Michael", "doing?"],
      correctOrder: ["What", "is", "Michael", "doing?"],
      successTitle: "Correto",
      successMessage: "What is Michael doing?",
    },
  },
  {
    key: "a2ic07s2",
    component: "Exercise3",
    needsSpeech: true,
    activity: {
      prompt: "Leia e responda: verdadeiro ou falso?",
      image: ICA2.A7S2,
      audioText: "Are you working today?",
      statement: 'Na pergunta "Are you work today?", a estrutura está correta para o Present Continuous.',
      textOnScreen: '"Are you work today?" está correta no Present Continuous.',
      options: ["true", "false"],
      correctAnswer: "false",
      successTitle: "Correto",
      successMessage: "False. O correto seria: Are you working today?",
      feedbackMessage: "A pergunta precisa de verbo com -ING: working.",
    },
  },
  {
    key: "a2ic07s3",
    component: "Exercise11",
    activity: {
      prompt: "Transforme as afirmações em perguntas:",
      title: "Digite a pergunta completa",
      placeholder: "Digite aqui",
      secondsPerWord: 10,
      words: [
        "Are you eating?",
        "Is he sleeping?",
        "Are they playing?",
        "Is she coming?",
        "Is it raining?",
      ],
      successTitle: "Correto",
      successMessage: "Você praticou a inversão do verbo BE.",
    },
  },
  {
    key: "a2ic07s4",
    component: "Exercise6",
    activity: {
      prompt: "Organize os blocos para perguntar onde a Sabrina está indo:",
      words: ["going?", "is", "Where", "Sabrina"],
      correctOrder: ["Where", "is", "Sabrina", "going?"],
      successTitle: "Correto",
      successMessage: "Where is Sabrina going?",
    },
  },
  {
    key: "a2ic07s5",
    component: "Exercise3",
    needsSpeech: true,
    activity: {
      prompt: "Leia e responda: verdadeiro ou falso?",
      image: ICA2.A7S5,
      audioText: "Why are you laughing?",
      statement: 'Em perguntas como "Why are you laughing?", o "are" deve vir antes do sujeito "you".',
      textOnScreen: 'Em "Why are you laughing?", o "are" vem antes de "you".',
      options: ["true", "false"],
      correctAnswer: "true",
      successTitle: "Correto",
      successMessage: "True. Em perguntas, o BE vem antes do sujeito.",
      feedbackMessage: "A ordem correta é WH + BE + sujeito + verbo-ing.",
    },
  },
  {
    key: "a2ic07s6",
    component: "Exercise11",
    activity: {
      prompt: "Complete a pergunta com What, Where, Why ou Who:",
      title: "Digite a WH-Word correta",
      placeholder: "Digite aqui",
      secondsPerWord: 8,
      words: ["What", "Where", "Why", "Who", "What"],
      successTitle: "Correto",
      successMessage: "Você escolheu as WH-Words certas.",
    },
  },
  {
    key: "a2ic07s7",
    component: "Exercise6",
    activity: {
      prompt: "Monte a pergunta para saber se seus amigos estão chegando:",
      words: ["arriving", "your friends", "Are", "now?"],
      correctOrder: ["Are", "your friends", "arriving", "now?"],
      successTitle: "Correto",
      successMessage: "Are your friends arriving now?",
    },
  },
  {
    key: "a2ic07s8",
    component: "Exercise3",
    needsSpeech: true,
    activity: {
      prompt: "Leia e responda: verdadeiro ou falso?",
      image: ICA2.A7S8,
      audioText: "Is Leo making a cake?",
      statement: 'A pergunta "Is Leo makeing a cake?" está escrita corretamente.',
      textOnScreen: '"Is Leo makeing a cake?" está escrita corretamente.',
      options: ["true", "false"],
      correctAnswer: "false",
      successTitle: "Correto",
      successMessage: "False. O correto é making, sem o E.",
      feedbackMessage: "Make perde o E antes de -ING: making.",
    },
  },
  {
    key: "a2ic07s9",
    component: "Exercise11",
    activity: {
      prompt: "Digite a pergunta completa usando as dicas:",
      title: "Escreva a pergunta",
      placeholder: "Digite aqui",
      secondsPerWord: 10,
      words: [
        "Are you studying?",
        "Is she dancing?",
        "Are they running?",
        "Is he working?",
        "Is it shining?",
      ],
      successTitle: "Correto",
      successMessage: "Você formou perguntas completas no Present Continuous.",
    },
  },
];

export default createA2LessonScreen(LESSON_SLIDES);
