import createA2LessonScreen from "./A2LessonScreen";
import { ICA2 } from "../../../../util/images";

const LESSON_SLIDES = [
  {
    key: "a2ic03s1",
    component: "Exercise17",
    activity: {
      label: "MÓDULO 1 • AULA 3",
      content: [
        "/blue{Making phrases}",
        "",
        "O mundo ao seu redor não é uma foto parada; é um vídeo acontecendo agora. Hoje você vai montar frases que capturam a vida no exato momento em que ela ganha forma.",
        "",
        "/blue{Tip - O Segredo da Ortografia}",
        "Termina em E? Ele desaparece: Make → Making.",
        "Verbo curto CVC? Dobra a última letra: Run → Running.",
        "O resto? Só adiciona -ing.",
      ],
      continueLabel: "Continuar",
    },
  },
  {
    key: "a2ic03s2",
    component: "Exercise20",
    activity: {
      prompt: "Leia e responda: verdadeiro ou falso?",
      image: ICA2.A3S2,
      statement:
        'Na frase "We are swiming in the pool", o verbo está escrito corretamente.',
      textOnScreen: '"We are swiming in the pool" está escrito corretamente.',
      options: ["true", "false"],
      correctAnswer: "false",
      successTitle: "Correto",
      successMessage: "False. O correto é swimming, com dois Ms.",
      feedbackMessage: "Swim vira swimming pela regra CVC.",
    },
  },
  {
    key: "a2ic03s3",
    component: "Exercise6",
    activity: {
      prompt: "Arraste os blocos para formar a frase correta:",
      words: ["is", "working", "John", "at", "the office", "today."],
      correctOrder: ["John", "is", "working", "at", "the office", "today."],
      successTitle: "Correto",
      successMessage: "John is working at the office today.",
    },
  },
  {
    key: "a2ic03s4",
    component: "Exercise4",
    activity: {
      prompt: 'Alguém pergunta: "Can you help me now?"',
      image: ICA2.A3S4,
      wrongSentence: "Escolha a resposta mais natural para agora.",
      options: ["I study English.", "I'm studying English right now, sorry!"],
      correctAnswer: "I'm studying English right now, sorry!",
      successTitle: "Correto",
      successMessage: 'Right now pede "I\'m studying".',
    },
  },
  {
    key: "a2ic03s5",
    component: "Exercise11",
    activity: {
      prompt: "Transforme os verbos para -ING. Cuidado com a escrita!",
      title: "Digite a forma com -ING",
      placeholder: "Digite aqui",
      secondsPerWord: 8,
      words: ["Stopping", "Writing", "Listening", "Getting", "Baking"],
      successTitle: "Correto",
      successMessage: "Você acertou as formas principais do -ING.",
    },
  },
  {
    key: "a2ic03s6",
    component: "Exercise5",
    activity: {
      prompt: 'Friend: "What are you doing?"',
      image: ICA2.A3S4,
      sentenceStart: "I",
      sentenceEnd: "for the exam.",
      options: ["am studying", "are studying"],
      correctAnswer: "am studying",
      successTitle: "Correto",
      successMessage: 'Com I, usamos "am": I am studying.',
    },
  },
  {
    key: "a2ic03s7",
    component: "Exercise5",
    activity: {
      prompt: 'Friend: "And your brother? Is he here?"',
      image: ICA2.A3S2,
      sentenceStart: "Yes, he",
      sentenceEnd: "in the garden.",
      options: ["is playing", "are playing"],
      correctAnswer: "is playing",
      successTitle: "Correto",
      successMessage: 'Com he, usamos "is".',
    },
  },
  {
    key: "a2ic03s8",
    component: "Exercise5",
    activity: {
      prompt: 'Friend: "I hear music! Is your sister there?"',
      image: ICA2.A1S8,
      sentenceStart: "Yes, she",
      sentenceEnd: ".",
      options: ["is dancing", "are dancing"],
      correctAnswer: "is dancing",
      successTitle: "Correto",
      successMessage: 'Com she, usamos "is".',
    },
  },
  {
    key: "a2ic03s9",
    component: "Exercise5",
    activity: {
      prompt: 'Friend: "I smell coffee! Is your father busy?"',
      image: ICA2.A1S5,
      sentenceStart: "Yes, he",
      sentenceEnd: "coffee.",
      options: ["is making", "is makeing"],
      correctAnswer: "is making",
      successTitle: "Correto",
      successMessage: "Make perde o E: making.",
    },
  },
  {
    key: "a2ic03s10",
    component: "Exercise5",
    activity: {
      prompt: 'Friend: "And your mother?"',
      image: ICA2.A2S10,
      sentenceStart: "She",
      sentenceEnd: ".",
      options: ["is working", "are working"],
      correctAnswer: "is working",
      successTitle: "Correto",
      successMessage: 'Com she, usamos "is working".',
    },
  },
  {
    key: "a2ic03s11",
    component: "Exercise5",
    activity: {
      prompt: 'Friend: "Look at the dog in the garden!"',
      image: ICA2.A2S7,
      sentenceStart: "Oh! It",
      sentenceEnd: ".",
      options: ["is running", "is runing"],
      correctAnswer: "is running",
      successTitle: "Correto",
      successMessage: "Run vira running com dois Ns.",
    },
  },
  {
    key: "a2ic03s12",
    component: "Exercise5",
    activity: {
      prompt: 'Friend: "What about your friends?"',
      image: ICA2.A2S9,
      sentenceStart: "They",
      sentenceEnd: ".",
      options: ["are waiting", "is waiting"],
      correctAnswer: "are waiting",
      successTitle: "Correto",
      successMessage: 'Com they, usamos "are".',
    },
  },
  {
    key: "a2ic03s13",
    component: "Exercise5",
    activity: {
      prompt: 'Friend: "Are we ready for the lesson?"',
      image: ICA2.A1S9,
      sentenceStart: "Yes, we",
      sentenceEnd: "now.",
      options: ["are starting", "is starting"],
      correctAnswer: "are starting",
      successTitle: "Correto",
      successMessage: 'Com we, usamos "are".',
    },
  },
  {
    key: "a2ic03s14",
    component: "Exercise5",
    activity: {
      prompt: 'Friend: "Is your neighbor outside?"',
      image: ICA2.A6S4,
      sentenceStart: "Yes, he",
      sentenceEnd: "the car.",
      options: ["is washing", "are washing"],
      correctAnswer: "is washing",
      successTitle: "Correto",
      successMessage: "He is washing the car.",
    },
  },
  {
    key: "a2ic03s15",
    component: "Exercise5",
    activity: {
      prompt: 'Friend: "Wow, everyone is busy!"',
      image: ICA2.A1S9,
      sentenceStart: "Yes, we",
      sentenceEnd: "a lot.",
      options: ["are learning", "is learning"],
      correctAnswer: "are learning",
      successTitle: "Correto",
      successMessage: "We are learning a lot.",
    },
  },
];

export default createA2LessonScreen(LESSON_SLIDES);
