import createA2LessonScreen from "./A2LessonScreen";
import { ICA2 } from "../../../../util/images";

const LESSON_SLIDES = [
  {
    key: "a2ic44s1",
    component: "Exercise17",
    activity: {
      label: "MÓDULO 5 • AULA 44",
      content: [
        "/blue{I'm the best}",
        "/blue{Regras? Não para eles!}",
        "Alguns adjetivos criam suas próprias palavras no superlativo.",
        'Você não vai usar "goodest" nem "most bad".',
        "Principais: Good, Bad e Far.",
      ],
      continueLabel: "Continuar",
    },
  },
  {
    key: "a2ic44s2",
    component: "Exercise14",
    needsSpeech: true,
    activity: {
      prompt: "Escute e escolha.",
      image: ICA2.A44S2,
      audioSource: require("../../../../../mp3/IC/A2/A44S2.mp3"),
      options: ["The best", "The better"],
      correctAnswer: "The best",
      correctOption: "The best",
      feedbackMessage: "Good vira the best.",
      successTitle: "Correto",
    },
  },
  {
    key: "a2ic44s3",
    component: "Exercise13",
    needsSpeech: true,
    activity: {
      prompt: 'Escreva "o melhor".',
      audioSource: require("../../../../../mp3/IC/A2/A44S3.mp3"),
      letters: ["B", "E", "S", "T"],
      correctWord: "BEST",
      successTitle: "Correto",
      successMessage: "Best.",
    },
  },
  {
    key: "a2ic44s4",
    component: "Exercise6",
    activity: {
      prompt: '"Você é o melhor amigo."',
      words: ["You", "are", "the best", "friend", "."],
      correctOrder: ["You", "are", "the best", "friend", "."],
      successTitle: "Correto",
      successMessage: "You are the best friend.",
    },
  },
  {
    key: "a2ic44s5",
    component: "Exercise5",
    activity: {
      prompt: "Dê a nota máxima para a pizza.",
      image: ICA2.A44S5,
      sentenceStart: "This is",
      sentenceEnd: "pizza in the city!",
      options: ["the best", "better"],
      correctAnswer: "the best",
      successTitle: "Correto",
      successMessage: "This is the best pizza in the city.",
    },
  },
  {
    key: "a2ic44s6",
    component: "Exercise14",
    needsSpeech: true,
    activity: {
      prompt: "Escute e escolha.",
      image: ICA2.A44S6,
      audioSource: require("../../../../../mp3/IC/A2/A44S6.mp3"),
      options: ["The worst", "The worse"],
      correctAnswer: "The worst",
      correctOption: "The worst",
      feedbackMessage: "Bad vira the worst.",
      successTitle: "Correto",
    },
  },
  {
    key: "a2ic44s7",
    component: "Exercise13",
    needsSpeech: true,
    activity: {
      prompt: 'Escreva "o pior".',
      audioSource: require("../../../../../mp3/IC/A2/A44S7.mp3"),
      letters: ["W", "O", "R", "S", "T"],
      correctWord: "WORST",
      successTitle: "Correto",
      successMessage: "Worst.",
    },
  },
  {
    key: "a2ic44s8",
    component: "Exercise6",
    activity: {
      prompt: '"Segunda-feira é o pior dia."',
      words: ["Monday", "is", "the worst", "day", "."],
      correctOrder: ["Monday", "is", "the worst", "day", "."],
      successTitle: "Correto",
      successMessage: "Monday is the worst day.",
    },
  },
  {
    key: "a2ic44s9",
    component: "Exercise5",
    activity: {
      prompt: "O filme foi um desastre.",
      image: ICA2.A44S9,
      sentenceStart: "That was",
      sentenceEnd: "movie ever.",
      options: ["worse", "the worst"],
      correctAnswer: "the worst",
      successTitle: "Correto",
      successMessage: "That was the worst movie ever.",
    },
  },
  {
    key: "a2ic44s10",
    component: "Exercise14",
    needsSpeech: true,
    activity: {
      prompt: "Escute e escolha.",
      image: ICA2.A44S10,
      audioSource: require("../../../../../mp3/IC/A2/A44S10.mp3"),
      options: ["The farther", "The farthest"],
      correctAnswer: "The farthest",
      correctOption: "The farthest",
      feedbackMessage: "Far vira the farthest.",
      successTitle: "Correto",
    },
  },
  {
    key: "a2ic44s11",
    component: "Exercise13",
    needsSpeech: true,
    activity: {
      prompt: 'Escreva "o mais longe".',
      audioSource: require("../../../../../mp3/IC/A2/A44S11.mp3"),
      letters: ["F", "A", "R", "T", "H", "E", "S", "T"],
      correctWord: "FARTHEST",
      successTitle: "Correto",
      successMessage: "Farthest.",
    },
  },
  {
    key: "a2ic44s12",
    component: "Exercise17",
    activity: {
      label: "Tabela",
      content: [
        "/blue{O Mapa dos Irregulares}",
        "Good → The best (o melhor)",
        "Bad → The worst (o pior)",
        "Far → The farthest / The furthest (o mais longe)",
        "Little → The least (o mínimo / o menos)",
        "Many / Much → The most (o máximo / o mais)",
      ],
      continueLabel: "Continuar",
    },
  },
  {
    key: "a2ic44s13",
    component: "Exercise19",
    activity: {
      prompt: "Escute o elogio do Camaleão e digite.",
      audioSource: require("../../../../../mp3/IC/A2/A44S13.mp3"),
      correctAnswer: "You are the best student in the class.",
      successTitle: "Correto",
      successMessage: "You are the best student in the class.",
    },
  },
  {
    key: "a2ic44s14",
    component: "Exercise16",
    activity: {
      prompt: "Gravação de áudio",
      instruction: 'Grave: "Chocolate is the best ice cream flavor!"',
      helperText: "Chocolate is the best ice cream flavor!",
      successTitle: "Muito bem!",
      successMessage: "Seu áudio foi gravado.",
    },
  },
  {
    key: "a2ic44s15",
    component: "Exercise17",
    activity: {
      label: "Final",
      content: [
        "/blue{Você venceu os rebeldes!}",
        'Agora você já conhece todos os tipos de superlativos: do "the most" ao "the best".',
      ],
      continueLabel: "Concluir",
    },
  },
];

export default createA2LessonScreen(LESSON_SLIDES);
