import createA2LessonScreen from "./A2LessonScreen";
import { ICA2 } from "../../../../util/images";

const LESSON_SLIDES = [
  {
    key: "a2ic20s1",
    component: "Exercise17",
    activity: {
      label: "MÓDULO 2 • AULA 20",
      content: [
        "/blue{Did you work?}",
        "/blue{Hora da Leitura!}",
        "Hoje vamos mergulhar em uma história real. Primeiro, vamos preparar seu ouvido e vocabulário com palavras-chave.",
      ],
      continueLabel: "Continuar",
    },
  },
  {
    key: "a2ic20s2",
    component: "Exercise17",
    activity: {
      label: "Vocabulário",
      content: ["A seguir você verá palavras essenciais para a Parte 1 da leitura."],
      continueLabel: "Continuar",
    },
  },
  {
    key: "a2ic20s3",
    component: "Exercise14",
    needsSpeech: true,
    activity: {
      prompt: "Vocabulário: escute e escolha.",
      image: ICA2.A20S3,
      audioSource: require("../../../../../mp3/IC/A2/A20S3.mp3"),
      audioText: "Woke up",
      options: ["Woke up", "Wake up"],
      correctAnswer: "Woke up",
      correctOption: "Woke up",
      feedbackMessage: "Woke up é o passado de wake up.",
      successTitle: "Correto",
    },
  },
  {
    key: "a2ic20s4",
    component: "Exercise14",
    needsSpeech: true,
    activity: {
      prompt: "Vocabulário: escute e escolha.",
      image: ICA2.A20S4,
      audioSource: require("../../../../../mp3/IC/A2/A20S4.mp3"),
      audioText: "Found",
      options: ["Find", "Found"],
      correctAnswer: "Found",
      correctOption: "Found",
      feedbackMessage: "Found é o passado de find.",
      successTitle: "Correto",
    },
  },
  {
    key: "a2ic20s5",
    component: "Exercise14",
    needsSpeech: true,
    activity: {
      prompt: "Vocabulário: escute e escolha.",
      image: ICA2.A20S5,
      audioSource: require("../../../../../mp3/IC/A2/A20S5.mp3"),
      audioText: "Spot",
      options: ["Spot", "Sport"],
      correctAnswer: "Spot",
      correctOption: "Spot",
      feedbackMessage: "Spot significa lugar ou ponto específico.",
      successTitle: "Correto",
    },
  },
  {
    key: "a2ic20s6",
    component: "Exercise14",
    needsSpeech: true,
    activity: {
      prompt: "Vocabulário: escute e escolha.",
      image: ICA2.A20S6,
      audioSource: require("../../../../../mp3/IC/A2/A20S6.mp3"),
      audioText: "Seafood",
      options: ["Seafood", "Seafoot"],
      correctAnswer: "Seafood",
      correctOption: "Seafood",
      feedbackMessage: "Seafood significa frutos do mar.",
      successTitle: "Correto",
    },
  },
  {
    key: "a2ic20s7",
    component: "Exercise17",
    activity: {
      label: "Dicionário",
      content: [
        "/blue{Dicionário de Bolso - Parte 1}",
        "Woke up: acordou",
        "Found: encontrou",
        "Spot: lugar / ponto",
        "Seafood: frutos do mar",
      ],
      continueLabel: "Continuar",
    },
  },
  {
    key: "a2ic20s8",
    component: "Exercise17",
    activity: {
      label: "Leitura",
      content: ["Agora que você já conhece as primeiras palavras, vamos começar a leitura."],
      continueLabel: "Continuar",
    },
  },
  {
    key: "a2ic20s9",
    component: "Exercise17",
    activity: {
      label: "Part 1",
      content: [
        "/blue{The Sunny Morning}",
        "Last Saturday, I woke up very early, at 6 AM. I called my friends and we went to the beach. The sun was hot and the ocean was beautiful. We found a perfect spot under a tree to relax.",
      ],
      continueLabel: "Continuar",
    },
  },
  {
    key: "a2ic20s10",
    component: "Exercise4",
    activity: {
      prompt: "What time did the person wake up?",
      image: ICA2.A20S10,
      wrongSentence: "Choose the correct answer.",
      options: ["At 8 AM.", "At 6 AM."],
      correctAnswer: "At 6 AM.",
      successTitle: "Correto",
      successMessage: "The person woke up at 6 AM.",
    },
  },
  {
    key: "a2ic20s11",
    component: "Exercise3",
    needsSpeech: true,
    activity: {
      prompt: "Responda: verdadeiro ou falso?",
      image: ICA2.A20S11,
      audioSource: require("../../../../../mp3/IC/A2/A20S11.mp3"),
      audioText: "I called my friends and we went to the beach.",
      statement: "The person went to the beach alone.",
      textOnScreen: "The person went to the beach alone.",
      options: ["true", "false"],
      correctAnswer: "false",
      successTitle: "Correto",
      successMessage: "False. A pessoa ligou para os amigos.",
      feedbackMessage: "O texto diz: I called my friends.",
    },
  },
  {
    key: "a2ic20s12",
    component: "Exercise14",
    needsSpeech: true,
    activity: {
      prompt: "Vocabulário: escute e escolha.",
      image: ICA2.A20S12,
      audioSource: require("../../../../../mp3/IC/A2/A20S12.mp3"),
      audioText: "Souvenirs",
      options: ["Souvenirs", "Sovereigns"],
      correctAnswer: "Souvenirs",
      correctOption: "Souvenirs",
      feedbackMessage: "Souvenirs são lembrancinhas.",
      successTitle: "Correto",
    },
  },
  {
    key: "a2ic20s13",
    component: "Exercise14",
    needsSpeech: true,
    activity: {
      prompt: "Vocabulário: escute e escolha.",
      image: ICA2.A20S13,
      audioSource: require("../../../../../mp3/IC/A2/A20S13.mp3"),
      audioText: "Local shop",
      options: ["Local shop", "Local soap"],
      correctAnswer: "Local shop",
      correctOption: "Local shop",
      feedbackMessage: "Local shop é uma loja local.",
      successTitle: "Correto",
    },
  },
  {
    key: "a2ic20s14",
    component: "Exercise17",
    activity: {
      label: "Part 2",
      content: [
        "/blue{Lunch Time}",
        "At 1 PM, we were hungry. We found a small restaurant near the water. We ate delicious seafood and drank juice. After lunch, we bought some souvenirs at a local shop to remember the trip.",
      ],
      continueLabel: "Continuar",
    },
  },
  {
    key: "a2ic20s15",
    component: "Exercise8",
    activity: {
      prompt: "Where did they buy the souvenirs?",
      image: ICA2.A20S15,
      options: ["At a local shop.", "At the restaurant."],
      correctAnswer: "At a local shop.",
      successTitle: "Correto",
      successMessage: "They bought souvenirs at a local shop.",
    },
  },
  {
    key: "a2ic20s16",
    component: "Exercise4",
    activity: {
      prompt: "What did they do after lunch?",
      image: ICA2.A20S16,
      wrongSentence: "Choose the correct answer.",
      options: ["They went swimming.", "They bought souvenirs."],
      correctAnswer: "They bought souvenirs.",
      successTitle: "Correto",
      successMessage: "After lunch, they bought souvenirs.",
    },
  },
  {
    key: "a2ic20s17",
    component: "Exercise14",
    needsSpeech: true,
    activity: {
      prompt: "Vocabulário: escute e escolha.",
      image: ICA2.A20S17,
      audioSource: require("../../../../../mp3/IC/A2/A20S17.mp3"),
      audioText: "Tired",
      options: ["Tired", "Tried"],
      correctAnswer: "Tired",
      correctOption: "Tired",
      feedbackMessage: "Tired significa cansado(a).",
      successTitle: "Correto",
    },
  },
  {
    key: "a2ic20s18",
    component: "Exercise14",
    needsSpeech: true,
    activity: {
      prompt: "Vocabulário: escute e escolha.",
      image: ICA2.A20S18,
      audioSource: require("../../../../../mp3/IC/A2/A20S18.mp3"),
      audioText: "Slept",
      options: ["Sleep", "Slept"],
      correctAnswer: "Slept",
      correctOption: "Slept",
      feedbackMessage: "Slept é o passado de sleep.",
      successTitle: "Correto",
    },
  },
  {
    key: "a2ic20s19",
    component: "Exercise5",
    activity: {
      prompt: "Part 3: The Night. Quanto tempo eles dormiram?",
      image: ICA2.A20S20,
      sentenceStart: "They slept for",
      sentenceEnd: ".",
      options: ["10 hours", "8 hours"],
      correctAnswer: "10 hours",
      successTitle: "Correto",
      successMessage: "They slept for 10 hours.",
    },
  },
  {
    key: "a2ic20s20",
    component: "Exercise4",
    activity: {
      prompt: "Why didn't they go home?",
      image: ICA2.A20S20,
      wrongSentence: "Choose the correct answer.",
      options: ["Because it was raining.", "Because they were very tired."],
      correctAnswer: "Because they were very tired.",
      successTitle: "Correto",
      successMessage: "They were very tired.",
    },
  },
  {
    key: "a2ic20s21",
    component: "Exercise5",
    activity: {
      prompt: "Quanto tempo eles dormiram?",
      image: ICA2.A20S20,
      sentenceStart: "They slept for",
      sentenceEnd: ".",
      options: ["10 hours", "8 hours"],
      correctAnswer: "10 hours",
      successTitle: "Correto",
      successMessage: "10 hours.",
    },
  },
  {
    key: "a2ic20s22",
    component: "Exercise12",
    activity: {
      prompt: "Resumo",
      instruction: "Resuma a história: começo, meio e fim.",
      helperText: "Tente usar: woke up, found, ate, bought e slept.",
      placeholder: "Digite seu resumo aqui",
      tipText: "Use frases curtas no passado.",
      successTitle: "Muito bem!",
      successMessage: "Você resumiu a história.",
    },
  },
  {
    key: "a2ic20s23",
    component: "Exercise17",
    activity: {
      label: "Final",
      content: [
        "/blue{Parabéns, Leitor!}",
        "Você concluiu a leitura completa e entendeu os detalhes. Usar contexto fixa melhor o passado dos verbos.",
      ],
      continueLabel: "Concluir",
    },
  },
];

export default createA2LessonScreen(LESSON_SLIDES);
