import createA2LessonScreen from "./A2LessonScreen";
import { ICA2, Images } from "../../../../util/images";

const LESSON_SLIDES = [
  {
    key: "a2ic30s1",
    component: "Exercise17",
    activity: {
      label: "MÓDULO 3 • AULA 30",
      content: [
        "/blue{Where's my cake?}",
        "/blue{Investigação do Passado!}",
        'Hoje vamos praticar perguntas sobre momentos específicos do passado: "What were you doing at 8 PM?"',
        "Fórmula: Wh-question + was/were + pessoa + verbo-ING?",
      ],
      continueLabel: "Continuar",
    },
  },
  {
    key: "a2ic30s2",
    component: "Exercise14",
    needsSpeech: true,
    activity: {
      prompt: "Vocabulário: escute e escolha.",
      image: ICA2.A30S2,
      audioSource: require("../../../../../mp3/IC/A2/A30S2.mp3"),
      options: ["Kitchen", "Chicken"],
      correctAnswer: "Kitchen",
      correctOption: "Kitchen",
      feedbackMessage: "Kitchen significa cozinha.",
      successTitle: "Correto",
    },
  },
  {
    key: "a2ic30s3",
    component: "Exercise14",
    needsSpeech: true,
    activity: {
      prompt: "Vocabulário: escute e escolha.",
      image: ICA2.A30S3,
      audioSource: require("../../../../../mp3/IC/A2/A30S3.mp3"),
      options: ["Singing", "Searching"],
      correctAnswer: "Searching",
      correctOption: "Searching",
      feedbackMessage: "Searching significa procurando.",
      successTitle: "Correto",
    },
  },
  {
    key: "a2ic30s4",
    component: "Exercise14",
    needsSpeech: true,
    activity: {
      prompt: "Vocabulário: escute e escolha.",
      image: ICA2.A30S4,
      audioSource: require("../../../../../mp3/IC/A2/A30S4.mp3"),
      options: ["Baking", "Banking"],
      correctAnswer: "Baking",
      correctOption: "Baking",
      feedbackMessage: "Baking é assar algo no forno.",
      successTitle: "Correto",
    },
  },
  {
    key: "a2ic30s5",
    component: "Exercise14",
    needsSpeech: true,
    activity: {
      prompt: "Vocabulário: escute e escolha.",
      image: ICA2.A30S5,
      audioSource: require("../../../../../mp3/IC/A2/A30S5.mp3"),
      options: ["Evidence", "Audience"],
      correctAnswer: "Evidence",
      correctOption: "Evidence",
      feedbackMessage: "Evidence significa evidência ou prova.",
      successTitle: "Correto",
    },
  },
  {
    key: "a2ic30s6",
    component: "Exercise17",
    activity: {
      label: "Dicionário",
      content: [
        "/blue{Dicionário do Investigador}",
        "Kitchen: cozinha.",
        "Searching: procurando.",
        "Baking: assando.",
        "Evidence: evidência / prova.",
      ],
      continueLabel: "Continuar",
    },
  },
  {
    key: "a2ic30s7",
    component: "Exercise14",
    needsSpeech: true,
    activity: {
      prompt: "Part 1: 8 PM. Leia enquanto ouve.",
      image: ICA2.A30S7,
      audioSource: require("../../../../../mp3/IC/A2/A30S7.mp3"),
      options: ["Leo was studying.", "Leo was baking."],
      correctAnswer: "Leo was studying.",
      correctOption: "Leo was studying.",
      feedbackMessage: "Leo disse que estava estudando no quarto.",
      successTitle: "Correto",
    },
  },
  {
    key: "a2ic30s8",
    component: "Exercise4",
    activity: {
      prompt: "What was Leo doing at 8 PM?",
      image: ICA2.A30S8,
      wrongSentence: "Choose the correct answer.",
      options: ["He was baking.", "He was studying."],
      correctAnswer: "He was studying.",
      successTitle: "Correto",
      successMessage: "Leo was studying.",
    },
  },
  {
    key: "a2ic30s9",
    component: "Exercise18",
    activity: {
      prompt: "Com quem o Leo estava estudando? Digite a frase.",
      scrambledWords: ["was", "He", "with", "studying", "dog", "his", "."],
      words: ["was", "He", "with", "studying", "dog", "his", "."],
      correctAnswer: "He was studying with his dog.",
      successTitle: "Correto",
      successMessage: "He was studying with his dog.",
    },
  },
  {
    key: "a2ic30s10",
    component: "Exercise14",
    needsSpeech: true,
    activity: {
      prompt: "Part 2: 9 PM. Leia enquanto ouve.",
      image: ICA2.A30S10,
      audioSource: require("../../../../../mp3/IC/A2/A30S10.mp3"),
      options: ["Sarah was baking a cake.", "Sarah was watching TV."],
      correctAnswer: "Sarah was baking a cake.",
      correctOption: "Sarah was baking a cake.",
      feedbackMessage: "Sarah estava assando um bolo de chocolate.",
      successTitle: "Correto",
    },
  },
  {
    key: "a2ic30s11",
    component: "Exercise14",
    needsSpeech: true,
    activity: {
      prompt: "What was Sarah doing at 9 PM?",
      image: ICA2.A30S11,
      audioText: "She was baking a cake.",
      options: ["She was baking a cake.", "She was watching TV."],
      correctAnswer: "She was baking a cake.",
      correctOption: "She was baking a cake.",
      feedbackMessage: "A imagem mostra Sarah tirando o bolo do forno.",
      successTitle: "Correto",
    },
  },
  {
    key: "a2ic30s12",
    component: "Exercise4",
    activity: {
      prompt: "Where were Sarah's friends at 9 PM?",
      image: ICA2.A30S12,
      wrongSentence: "Choose the correct answer.",
      options: ["In the kitchen.", "In the living room."],
      correctAnswer: "In the living room.",
      successTitle: "Correto",
      successMessage: "They were watching TV in the living room.",
    },
  },
  {
    key: "a2ic30s13",
    component: "Exercise17",
    activity: {
      label: "Part 3",
      content: [
        "/blue{The Missing Piece}",
        "At 10 PM, a piece of cake was missing! Sarah was washing the dishes. Leo confessed: he was searching for a snack and ate it. Case closed!",
      ],
      continueLabel: "Continuar",
    },
  },
  {
    key: "a2ic30s14",
    component: "Exercise19",
    activity: {
      prompt: "Escute a pergunta do detetive e digite.",
      audioSource: require("../../../../../mp3/IC/A2/A30S14.mp3"),
      correctAnswer: "What were you doing at 10 PM?",
      successTitle: "Correto",
      successMessage: "What were you doing at 10 PM?",
    },
  },
  {
    key: "a2ic30s15",
    component: "Exercise4",
    activity: {
      prompt: "Why did Leo eat the cake?",
      image: ICA2.A30S15,
      wrongSentence: "Choose the correct answer.",
      options: [
        "Because he was searching for a snack.",
        "Because Sarah gave it to him.",
      ],
      correctAnswer: "Because he was searching for a snack.",
      successTitle: "Correto",
      successMessage: "Leo estava procurando um lanche.",
    },
  },
  {
    key: "a2ic30s16",
    component: "Exercise16",
    activity: {
      prompt: "Gravação de áudio",
      image: Images.ex16,
      tipButtonLabel: "Tip",
      instruction:
        'Responda à pergunta: "What were you doing at 8 PM yesterday?"',
      helperText: 'Comece com "I was..." e use um verbo com ING.',
      successTitle: "Muito bem!",
      successMessage: "Seu áudio foi gravado.",
    },
  },
  {
    key: "a2ic30s17",
    component: "Exercise17",
    activity: {
      label: "Final",
      content: [
        "/blue{Caso Encerrado!}",
        "Você dominou as perguntas no Past Continuous e já consegue investigar o que qualquer pessoa estava fazendo.",
      ],
      continueLabel: "Concluir",
    },
  },
];

export default createA2LessonScreen(LESSON_SLIDES);
