import createA2LessonScreen from "./A2LessonScreen";
import { ICA2 } from "../../../../util/images";

const LESSON_SLIDES = [
  {
    key: "a2ic31s1",
    component: "Exercise17",
    activity: {
      label: "MÓDULO 3 • AULA 31",
      content: [
        "/blue{Booking a flight}",
        "/blue{Próxima Parada: Sucesso!}",
        "Hoje vamos aprender como reservar passagens online.",
        'Você vai dominar termos como "one-way", "round-trip", departure e arrival.',
      ],
      continueLabel: "Continuar",
    },
  },
  {
    key: "a2ic31s2",
    component: "Exercise14",
    needsSpeech: true,
    activity: {
      prompt: "Escute e escolha.",
      image: ICA2.A31S2,
      audioSource: require("../../../../../mp3/IC/A2/A31S2.mp3"),
      audioText: "One-way ticket",
      options: ["One-way ticket", "On-way ticket"],
      correctAnswer: "One-way ticket",
      correctOption: "One-way ticket",
      feedbackMessage: "One-way significa só ida.",
      successTitle: "Correto",
    },
  },
  {
    key: "a2ic31s3",
    component: "Exercise14",
    needsSpeech: true,
    activity: {
      prompt: "Escute e escolha.",
      image: ICA2.A31S3,
      audioSource: require("../../../../../mp3/IC/A2/A31S3.mp3"),
      audioText: "Round-trip",
      options: ["Road-trip", "Round-trip"],
      correctAnswer: "Round-trip",
      correctOption: "Round-trip",
      feedbackMessage: "Round-trip significa ida e volta.",
      successTitle: "Correto",
    },
  },
  {
    key: "a2ic31s4",
    component: "Exercise14",
    needsSpeech: true,
    activity: {
      prompt: "Escute e escolha.",
      image: ICA2.A31S4,
      audioSource: require("../../../../../mp3/IC/A2/A31S4.mp3"),
      audioText: "Departure",
      options: ["Departure", "Department"],
      correctAnswer: "Departure",
      correctOption: "Departure",
      feedbackMessage: "Departure significa partida.",
      successTitle: "Correto",
    },
  },
  {
    key: "a2ic31s5",
    component: "Exercise14",
    needsSpeech: true,
    activity: {
      prompt: "Escute e escolha.",
      image: ICA2.A31S5,
      audioSource: require("../../../../../mp3/IC/A2/A31S5.mp3"),
      audioText: "Arrival",
      options: ["Rival", "Arrival"],
      correctAnswer: "Arrival",
      correctOption: "Arrival",
      feedbackMessage: "Arrival significa chegada.",
      successTitle: "Correto",
    },
  },
  {
    key: "a2ic31s6",
    component: "Exercise17",
    activity: {
      label: "Dicionário",
      content: [
        "/blue{Dicionário do Viajante}",
        "One-way: só ida.",
        "Round-trip: ida e volta.",
        "Departure: partida / saída.",
        "Arrival: chegada.",
      ],
      continueLabel: "Continuar",
    },
  },
  {
    key: "a2ic31s7",
    component: "Exercise18",
    activity: {
      prompt: "Digite a frase para buscar uma passagem de ida e volta.",
      scrambledWords: ["I", "need", "a", "round-trip", "ticket", "."],
      words: ["I", "need", "a", "round-trip", "ticket", "."],
      correctAnswer: "I need a round-trip ticket.",
      successTitle: "Correto",
      successMessage: "I need a round-trip ticket.",
    },
  },
  {
    key: "a2ic31s8",
    component: "Exercise18",
    activity: {
      prompt: "Pergunte sobre a saída do trem.",
      scrambledWords: ["What", "time", "is", "the", "departure", "?"],
      words: ["What", "time", "is", "the", "departure", "?"],
      correctAnswer: "What time is the departure?",
      successTitle: "Correto",
      successMessage: "What time is the departure?",
    },
  },
  {
    key: "a2ic31s9",
    component: "Exercise19",
    activity: {
      prompt: "Escute a instrução de embarque e digite.",
      audioSource: require("../../../../../mp3/IC/A2/A31S9.mp3"),
      audioText: "The flight leaves from gate five.",
      correctAnswer: "The flight leaves from gate five.",
      successTitle: "Correto",
      successMessage: "The flight leaves from gate five.",
    },
  },
  {
    key: "a2ic31s10",
    component: "Exercise19",
    activity: {
      prompt: "Escute o desejo do passageiro e digite.",
      audioSource: require("../../../../../mp3/IC/A2/A31S10.mp3"),
      audioText: "I would like to book a train to London.",
      correctAnswer: "I would like to book a train to London.",
      successTitle: "Correto",
      successMessage: "I would like to book a train to London.",
    },
  },
  {
    key: "a2ic31s11",
    component: "Exercise8",
    activity: {
      prompt: "What time does the train leave?",
      image: ICA2.A31S11,
      options: ["At 10:00 AM.", "At 9:00 AM."],
      correctAnswer: "At 10:00 AM.",
      successTitle: "Correto",
      successMessage: "The departure is at 10:00 AM.",
    },
  },
  {
    key: "a2ic31s12",
    component: "Exercise4",
    activity: {
      prompt: "Você quer viajar, mas não quer voltar. Qual opção você marca no site?",
      image: ICA2.A31S12,
      wrongSentence: "Choose the correct answer.",
      options: ["Round-trip", "One-way"],
      correctAnswer: "One-way",
      successTitle: "Correto",
      successMessage: "One-way é passagem só de ida.",
    },
  },
  {
    key: "a2ic31s13",
    component: "Exercise16",
    activity: {
      prompt: "Gravação de áudio",
      instruction: 'Grave: "I\'d like to book a round-trip ticket to New York, please."',
      helperText: "I'd like to book a round-trip ticket to New York, please.",
      successTitle: "Muito bem!",
      successMessage: "Seu áudio foi gravado.",
    },
  },
  {
    key: "a2ic31s14",
    component: "Exercise17",
    activity: {
      label: "Final",
      content: [
        "/blue{Check-in Concluído!}",
        "Agora você já sabe os termos principais para reservar suas próprias viagens.",
      ],
      continueLabel: "Concluir",
    },
  },
];

export default createA2LessonScreen(LESSON_SLIDES);
