import createA2LessonScreen from "./A2LessonScreen";
import { ICA2 } from "../../../../util/images";

const LESSON_SLIDES = [
  {
    key: "a2ic14s1",
    component: "Exercise4",
    activity: {
      prompt: 'Como dizemos "Eu vi um filme ontem"?',
      image: ICA2.A14S1,
      wrongSentence: "Eu vi um filme ontem.",
      options: ["I saw a movie yesterday.", "I seed a movie yesterday.", "I see a movie yesterday."],
      correctAnswer: "I saw a movie yesterday.",
      successTitle: "Correto",
      successMessage: "See é irregular: no passado vira saw.",
    },
  },
  {
    key: "a2ic14s2",
    component: "Exercise14",
    needsSpeech: true,
    activity: {
      prompt: "Ouça o áudio e selecione a forma do passado.",
      image: ICA2.A14S2,
      audioSource: require("../../../../../mp3/IC/A2/A14S2.mp3"),
      audioText: "Ate",
      options: ["Eat", "Ate"],
      correctAnswer: "Ate",
      correctOption: "Ate",
      feedbackMessage: "Eat vira ate no passado.",
      successTitle: "Correto",
    },
  },
  {
    key: "a2ic14s3",
    component: "Exercise14",
    needsSpeech: true,
    activity: {
      prompt: "Ouça o áudio e selecione a forma do passado.",
      image: ICA2.A14S3,
      audioSource: require("../../../../../mp3/IC/A2/A14S3.mp3"),
      audioText: "Saw",
      options: ["See", "Saw"],
      correctAnswer: "Saw",
      correctOption: "Saw",
      feedbackMessage: "See vira saw no passado.",
      successTitle: "Correto",
    },
  },
  {
    key: "a2ic14s4",
    component: "Exercise14",
    needsSpeech: true,
    activity: {
      prompt: "Ouça o áudio e selecione a forma do passado.",
      image: ICA2.A14S4,
      audioSource: require("../../../../../mp3/IC/A2/A14S4.mp3"),
      audioText: "Drank",
      options: ["Drink", "Drank"],
      correctAnswer: "Drank",
      correctOption: "Drank",
      feedbackMessage: "Drink vira drank no passado.",
      successTitle: "Correto",
    },
  },
  {
    key: "a2ic14s5",
    component: "Exercise14",
    needsSpeech: true,
    activity: {
      prompt: "Ouça o áudio e selecione a forma do passado.",
      image: ICA2.A14S5,
      audioSource: require("../../../../../mp3/IC/A2/A14S5.mp3"),
      audioText: "Told",
      options: ["Tell", "Told"],
      correctAnswer: "Told",
      correctOption: "Told",
      feedbackMessage: "Tell vira told no passado.",
      successTitle: "Correto",
    },
  },
  {
    key: "a2ic14s6",
    component: "Exercise14",
    needsSpeech: true,
    activity: {
      prompt: "Ouça o áudio e selecione a forma do passado.",
      image: ICA2.A14S6,
      audioSource: require("../../../../../mp3/IC/A2/A14S6.mp3"),
      audioText: "Gave",
      options: ["Give", "Gave"],
      correctAnswer: "Gave",
      correctOption: "Gave",
      feedbackMessage: "Give vira gave no passado.",
      successTitle: "Correto",
    },
  },
  {
    key: "a2ic14s7",
    component: "Exercise17",
    activity: {
      label: "MÓDULO 2 • AULA 14",
      content: [
        "/blue{I took a shower}",
        "A família dos irregulares é grande. Hoje vamos falar de comida, segredos e do que vimos por aí.",
        "",
        "/blue{Mudança de Vogal}",
        "Muitos irregulares mudam apenas a vogal do meio.",
        "Drink → Drank",
        "Give → Gave",
        "See → Saw",
      ],
      continueLabel: "Continuar",
    },
  },
  {
    key: "a2ic14s8",
    component: "Exercise1",
    activity: {
      prompt: "Conecte o presente com seu passado irregular.",
      pairs: [
        { en: "See", pt: "Saw" },
        { en: "Eat", pt: "Ate" },
        { en: "Tell", pt: "Told" },
        { en: "Give", pt: "Gave" },
        { en: "Drink", pt: "Drank" },
      ],
      successTitle: "Correto",
      successMessage: "Você conectou os irregulares corretamente.",
    },
  },
  {
    key: "a2ic14s9",
    component: "Exercise17",
    activity: {
      label: "Tip",
      content: [
        "/blue{Cuidado com o SAW!}",
        "Saw tem som de Ó bem aberto. O W é mudo.",
      ],
      continueLabel: "Continuar",
    },
  },
  {
    key: "a2ic14s10",
    component: "Exercise13",
    needsSpeech: true,
    activity: {
      prompt: 'Ordene as letras para formar o passado de "TELL".',
      audioSource: require("../../../../../mp3/IC/A2/A14S10.mp3"),
      audioText: "Told",
      letters: ["T", "O", "L", "D"],
      correctWord: "TOLD",
      successTitle: "Correto",
      successMessage: "Tell vira told.",
    },
  },
  {
    key: "a2ic14s11",
    component: "Exercise5",
    activity: {
      prompt: 'Complete com o passado de "DRINK".',
      image: ICA2.A14S11,
      sentenceStart: "I",
      sentenceEnd: "a lot of water after the gym.",
      options: ["drunk", "drank"],
      correctAnswer: "drank",
      successTitle: "Correto",
      successMessage: "Drink vira drank no Simple Past.",
    },
  },
  {
    key: "a2ic14s12",
    component: "Exercise8",
    activity: {
      prompt: "Clique na frase que descreve a imagem.",
      image: ICA2.A14S12,
      options: ["He ate a whole pizza last night!", "He eated a whole pizza last night."],
      correctAnswer: "He ate a whole pizza last night!",
      successTitle: "Correto",
      successMessage: "Eat é irregular: ate, não eated.",
    },
  },
  {
    key: "a2ic14s13",
    component: "Exercise6",
    activity: {
      prompt: "Coloque as palavras na ordem correta.",
      words: ["He", "gave", "me", "a", "present", "yesterday", "."],
      correctOrder: ["He", "gave", "me", "a", "present", "yesterday", "."],
      successTitle: "Correto",
      successMessage: "He gave me a present yesterday.",
    },
  },
  {
    key: "a2ic14s14",
    component: "Exercise3",
    needsSpeech: true,
    activity: {
      prompt: "Ouça e responda.",
      image: ICA2.A14S14,
      audioSource: require("../../../../../mp3/IC/A2/A14S14.mp3"),
      audioText: "My mom told me a secret this morning. She's buying a new car!",
      statement: "The mom told a secret.",
      textOnScreen: "The mom told a secret.",
      options: ["true", "false"],
      correctAnswer: "true",
      successTitle: "Correto",
      successMessage: "True. O áudio diz: My mom told me a secret.",
      feedbackMessage: "Told me significa me contou.",
    },
  },
  {
    key: "a2ic14s15",
    component: "Exercise2",
    activity: {
      prompt: "Complete o relato.",
      paragraphs: [
        [
          "We ",
          { id: "b1", answer: "ate", options: ["ate", "eat"] },
          " pasta and ",
          { id: "b2", answer: "drank", options: ["drank", "drunk"] },
          " Italian wine.",
        ],
      ],
      successTitle: "Correto",
      successMessage: "Ate e drank são formas irregulares no passado.",
    },
  },
  {
    key: "a2ic14s16",
    component: "Exercise17",
    activity: {
      label: "Tip cultural",
      content: [
        "/blue{Fofoca em Inglês?}",
        "Se você quer contar que alguém te disse algo, use TOLD.",
        "Told sempre vem acompanhado de quem ouviu: told me, told him, told her.",
        'Exemplo: "She told me a secret."',
      ],
      continueLabel: "Continuar",
    },
  },
  {
    key: "a2ic14s17",
    component: "Exercise12",
    activity: {
      prompt: "Freer Practice",
      instruction: "O que você comeu e bebeu hoje?",
      helperText: "Exemplo: I ate bread and drank coffee.",
      placeholder: "Digite sua frase aqui",
      tipText: "Use ate e drank.",
      successTitle: "Muito bem!",
      successMessage: "Você usou irregulares de comida e bebida.",
    },
  },
  {
    key: "a2ic14s18",
    component: "Exercise16",
    activity: {
      prompt: "Freer Practice - Áudio",
      instruction: "Pense no último filme que você viu. Diga o nome do filme.",
      helperText: "Exemplo: I saw Avatar.",
      tipText: "Use saw para falar de algo que você viu.",
      successTitle: "Muito bem!",
      successMessage: "Seu áudio foi gravado.",
    },
  },
  {
    key: "a2ic14s20",
    component: "Exercise17",
    activity: {
      label: "Desafio",
      content: [
        "/blue{Desafio de Escrita!}",
        "Você verá um verbo no presente e terá 5 segundos para digitar a forma correta do passado.",
      ],
      continueLabel: "Começar",
    },
  },
  {
    key: "a2ic14s21",
    component: "Exercise11",
    activity: {
      prompt: "Digite o passado dos verbos:",
      title: "Escreva rápido",
      placeholder: "Digite aqui",
      secondsPerWord: 5,
      words: ["Ate", "Saw", "Told", "Gave", "Drank"],
      successTitle: "Correto",
      successMessage: "Você praticou mais cinco irregulares essenciais.",
    },
  },
  {
    key: "a2ic14s22",
    component: "Exercise17",
    activity: {
      label: "Final",
      content: [
        "/blue{Missão Cumprida!}",
        "Agora esses rebeldes são seus melhores amigos. Continue praticando os áudios para ficar com a pronúncia mais natural.",
      ],
      continueLabel: "Concluir",
    },
  },
];

export default createA2LessonScreen(LESSON_SLIDES);
