import createA2LessonScreen from "./A2LessonScreen";
import { ICA2 } from "../../../../util/images";

const LESSON_SLIDES = [
  {
    key: "a2ic39s1",
    component: "Exercise17",
    activity: {
      label: "MÓDULO 4 • AULA 39",
      content: [
        "/blue{He's as tall as me!}",
        "/blue{O Sanduíche de Igualdade!}",
        "Quando duas coisas são iguais em alguma característica, usamos AS... AS.",
        "Aqui não tem regra de -er ou more. O adjetivo fica normal no meio.",
        "Fórmula: AS + adjetivo + AS.",
      ],
      continueLabel: "Continuar",
    },
  },
  {
    key: "a2ic39s2",
    component: "Exercise14",
    needsSpeech: true,
    activity: {
      prompt: "Escute e escolha.",
      image: ICA2.A39S2,
      audioSource: require("../../../../../mp3/IC/A2/A39S2.mp3"),
      audioText: "As tall as",
      options: ["As tall less", "As tall as"],
      correctAnswer: "As tall as",
      correctOption: "As tall as",
      feedbackMessage: "As tall as significa tão alto quanto.",
      successTitle: "Correto",
    },
  },
  {
    key: "a2ic39s3",
    component: "Exercise14",
    needsSpeech: true,
    activity: {
      prompt: "Escute e escolha.",
      image: ICA2.A39S3,
      audioSource: require("../../../../../mp3/IC/A2/A39S3.mp3"),
      audioText: "As fast as",
      options: ["As fast less", "As fast as"],
      correctAnswer: "As fast as",
      correctOption: "As fast as",
      feedbackMessage: "As fast as significa tão rápido quanto.",
      successTitle: "Correto",
    },
  },
  {
    key: "a2ic39s4",
    component: "Exercise14",
    needsSpeech: true,
    activity: {
      prompt: "Escute e escolha.",
      image: ICA2.A39S4,
      audioSource: require("../../../../../mp3/IC/A2/A39S4.mp3"),
      audioText: "As big as",
      options: ["As big", "As big as"],
      correctAnswer: "As big as",
      correctOption: "As big as",
      feedbackMessage: "As big as significa tão grande quanto.",
      successTitle: "Correto",
    },
  },
  {
    key: "a2ic39s5",
    component: "Exercise13",
    needsSpeech: true,
    activity: {
      prompt: "Escreva a palavra que forma o sanduíche.",
      audioSource: require("../../../../../mp3/IC/A2/A39S5.mp3"),
      audioText: "As",
      letters: ["A", "S"],
      correctWord: "AS",
      successTitle: "Correto",
      successMessage: "As.",
    },
  },
  {
    key: "a2ic39s6",
    component: "Exercise5",
    activity: {
      prompt: "O Camaleão e seu irmão têm a mesma altura.",
      image: ICA2.A39S6,
      sentenceStart: "Cam is",
      sentenceEnd: "tall ______ his brother.",
      options: ["as", "better"],
      correctAnswer: "as",
      successTitle: "Correto",
      successMessage: "Cam is as tall as his brother.",
    },
  },
  {
    key: "a2ic39s7",
    component: "Exercise6",
    activity: {
      prompt: "Organize a frase de igualdade.",
      words: ["English", "is", "as important as", "Spanish", "."],
      correctOrder: ["English", "is", "as important as", "Spanish", "."],
      successTitle: "Correto",
      successMessage: "English is as important as Spanish.",
    },
  },
  {
    key: "a2ic39s8",
    component: "Exercise17",
    activity: {
      label: "Expressões",
      content: [
        "/blue{Mais Combinações}",
        "As cold as ice: tão frio quanto gelo.",
        "As easy as ABC: tão fácil quanto o ABC.",
        "As happy as a clam: expressão comum para muito feliz.",
        "As strong as an ox: tão forte quanto um boi.",
      ],
      continueLabel: "Continuar",
    },
  },
  {
    key: "a2ic39s9",
    component: "Exercise17",
    activity: {
      label: "Tip",
      content: [
        "/blue{Não é tão... quanto}",
        "Para dizer que algo não é igual, colocamos not na frente.",
        'Exemplo: "Soda is not as healthy as water."',
      ],
      continueLabel: "Continuar",
    },
  },
  {
    key: "a2ic39s10",
    component: "Exercise14",
    needsSpeech: true,
    activity: {
      prompt: "Escute e escolha.",
      image: ICA2.A39S10,
      audioSource: require("../../../../../mp3/IC/A2/A39S10.mp3"),
      audioText: "Not as expensive as",
      options: ["As expensive less", "Not as expensive as"],
      correctAnswer: "Not as expensive as",
      correctOption: "Not as expensive as",
      feedbackMessage: "Not as expensive as significa não tão caro quanto.",
      successTitle: "Correto",
    },
  },
  {
    key: "a2ic39s11",
    component: "Exercise14",
    needsSpeech: true,
    activity: {
      prompt: "Escute e escolha.",
      image: ICA2.A39S11,
      audioSource: require("../../../../../mp3/IC/A2/A39S11.mp3"),
      audioText: "Not as hot as",
      options: ["Not as hot less", "Not as hot as"],
      correctAnswer: "Not as hot as",
      correctOption: "Not as hot as",
      feedbackMessage: "Not as hot as significa não tão quente quanto.",
      successTitle: "Correto",
    },
  },
  {
    key: "a2ic39s12",
    component: "Exercise13",
    needsSpeech: true,
    activity: {
      prompt: "Escreva a palavra de negação.",
      audioSource: require("../../../../../mp3/IC/A2/A39S12.mp3"),
      audioText: "Not",
      letters: ["N", "O", "T"],
      correctWord: "NOT",
      successTitle: "Correto",
      successMessage: "Not.",
    },
  },
  {
    key: "a2ic39s13",
    component: "Exercise6",
    activity: {
      prompt: "Organize a comparação negativa.",
      words: ["My car", "is not", "as fast as", "yours", "."],
      correctOrder: ["My car", "is not", "as fast as", "yours", "."],
      successTitle: "Correto",
      successMessage: "My car is not as fast as yours.",
    },
  },
  {
    key: "a2ic39s14",
    component: "Exercise19",
    activity: {
      prompt: "Escute e digite a frase completa.",
      audioSource: require("../../../../../mp3/IC/A2/A39S14.mp3"),
      audioText: "This book is as interesting as the movie.",
      correctAnswer: "This book is as interesting as the movie.",
      successTitle: "Correto",
      successMessage: "This book is as interesting as the movie.",
    },
  },
  {
    key: "a2ic39s15",
    component: "Exercise16",
    activity: {
      prompt: "Gravação de áudio",
      instruction: "Grave uma comparação de igualdade.",
      helperText: 'Exemplo: "My mom is as intelligent as my dad."',
      successTitle: "Muito bem!",
      successMessage: "Seu áudio foi gravado.",
    },
  },
  {
    key: "a2ic39s16",
    component: "Exercise17",
    activity: {
      label: "Final",
      content: [
        "/blue{Mestre Supremo dos Comparativos!}",
        "Você completou a trilha: mais, menos, muito mais, um pouquinho mais e igual.",
      ],
      continueLabel: "Concluir",
    },
  },
];

export default createA2LessonScreen(LESSON_SLIDES);
