import createA2LessonScreen from "./A2LessonScreen";
import { ICA2, Images } from "../../../../util/images";

const LESSON_SLIDES = [
  {
    key: "a2ic43s1",
    component: "Exercise17",
    activity: {
      label: "MÓDULO 5 • AULA 43",
      content: [
        "/blue{I'm the fastest one.}",
        "/blue{Tchau, Y! Bem-vindo, IEST!}",
        "Se o adjetivo termina em consoante + Y, jogamos o Y fora e colocamos -IEST no final.",
        "Fórmula: THE + adjetivo sem Y + IEST.",
        "Happy → The happiest.",
      ],
      continueLabel: "Continuar",
    },
  },
  {
    key: "a2ic43s2",
    component: "Exercise14",
    needsSpeech: true,
    activity: {
      prompt: "Escute e escolha.",
      image: ICA2.A43S2,
      audioSource: require("../../../../../mp3/IC/A2/A43S2.mp3"),
      options: ["The happiest", "The happier"],
      correctAnswer: "The happiest",
      correctOption: "The happiest",
      feedbackMessage: "Happy vira the happiest.",
      successTitle: "Correto",
    },
  },
  {
    key: "a2ic43s3",
    component: "Exercise14",
    needsSpeech: true,
    activity: {
      prompt: "Escute e escolha.",
      image: ICA2.A43S3,
      audioSource: require("../../../../../mp3/IC/A2/A43S3.mp3"),
      options: ["The easier", "The easiest"],
      correctAnswer: "The easiest",
      correctOption: "The easiest",
      feedbackMessage: "Easy vira the easiest.",
      successTitle: "Correto",
    },
  },
  {
    key: "a2ic43s4",
    component: "Exercise14",
    needsSpeech: true,
    activity: {
      prompt: "Escute e escolha.",
      image: ICA2.A43S4,
      audioSource: require("../../../../../mp3/IC/A2/A43S4.mp3"),
      options: ["The funniest", "The funnier"],
      correctAnswer: "The funniest",
      correctOption: "The funniest",
      feedbackMessage: "Funny vira the funniest.",
      successTitle: "Correto",
    },
  },
  {
    key: "a2ic43s5",
    component: "Exercise13",
    needsSpeech: true,
    activity: {
      prompt: "Escreva o mais fácil. Lembre-se do I.",
      audioSource: require("../../../../../mp3/IC/A2/A43S5.mp3"),
      letters: ["E", "A", "S", "I", "E", "S", "T"],
      correctWord: "EASIEST",
      successTitle: "Correto",
      successMessage: "Easiest.",
    },
  },
  {
    key: "a2ic43s6",
    component: "Exercise6",
    activity: {
      prompt: '"Este é o dia mais feliz da minha vida."',
      words: ["Today", "is", "the happiest", "day", "of my life", "."],
      correctOrder: ["Today", "is", "the happiest", "day", "of my life", "."],
      successTitle: "Correto",
      successMessage: "Today is the happiest day of my life.",
    },
  },
  {
    key: "a2ic43s7",
    component: "Exercise17",
    activity: {
      label: "Lista",
      content: [
        "/blue{+5 Adjetivos com Y}",
        "Dirty → The dirtiest",
        "Lucky → The luckiest",
        "Healthy → The healthiest",
        "Lazy → The laziest",
        "Busy → The busiest",
      ],
      continueLabel: "Continuar",
    },
  },
  {
    key: "a2ic43s8",
    component: "Exercise17",
    activity: {
      label: "Tip",
      content: [
        "/blue{A Dobra do CVC!}",
        "No superlativo, também dobramos a última letra antes de colocar -EST.",
        "Big → The biggest.",
      ],
      continueLabel: "Continuar",
    },
  },
  {
    key: "a2ic43s9",
    component: "Exercise14",
    needsSpeech: true,
    activity: {
      prompt: "Escute e escolha.",
      image: ICA2.A43S9,
      audioSource: require("../../../../../mp3/IC/A2/A43S9.mp3"),
      options: ["The biggest", "The bigger"],
      correctAnswer: "The biggest",
      correctOption: "The biggest",
      feedbackMessage: "Big vira the biggest, com G dobrado.",
      successTitle: "Correto",
    },
  },
  {
    key: "a2ic43s10",
    component: "Exercise14",
    needsSpeech: true,
    activity: {
      prompt: "Escute e escolha.",
      image: ICA2.A43S10,
      audioSource: require("../../../../../mp3/IC/A2/A43S10.mp3"),
      options: ["The hotest", "The hottest"],
      correctAnswer: "The hottest",
      correctOption: "The hottest",
      feedbackMessage: "Hot vira the hottest, com T dobrado.",
      successTitle: "Correto",
    },
  },
  {
    key: "a2ic43s11",
    component: "Exercise14",
    needsSpeech: true,
    activity: {
      prompt: "Escute e escolha.",
      image: ICA2.A43S11,
      audioSource: require("../../../../../mp3/IC/A2/A43S11.mp3"),
      options: ["The sadder", "The saddest"],
      correctAnswer: "The saddest",
      correctOption: "The saddest",
      feedbackMessage: "Sad vira the saddest, com D dobrado.",
      successTitle: "Correto",
    },
  },
  {
    key: "a2ic43s12",
    component: "Exercise13",
    needsSpeech: true,
    activity: {
      prompt: "Escreva maior com a letra dobrada.",
      audioSource: require("../../../../../mp3/IC/A2/A43S12.mp3"),
      letters: ["B", "I", "G", "G", "E", "S", "T"],
      correctWord: "BIGGEST",
      successTitle: "Correto",
      successMessage: "Biggest.",
    },
  },
  {
    key: "a2ic43s13",
    component: "Exercise6",
    activity: {
      prompt: '"O deserto do Saara é o lugar mais quente."',
      words: ["The Sahara", "is", "the hottest", "place", "."],
      correctOrder: ["The Sahara", "is", "the hottest", "place", "."],
      successTitle: "Correto",
      successMessage: "The Sahara is the hottest place.",
    },
  },
  {
    key: "a2ic43s14",
    component: "Exercise17",
    activity: {
      label: "Lista",
      content: [
        "/blue{+5 Adjetivos CVC}",
        "Fat → The fattest",
        "Mad → The maddest",
        "Wet → The wettest",
        "Fit → The fittest",
        "Slim → The slimmest",
      ],
      continueLabel: "Continuar",
    },
  },
  {
    key: "a2ic43s15",
    component: "Exercise19",
    activity: {
      prompt: "Escute e digite com atenção à escrita.",
      audioSource: require("../../../../../mp3/IC/A2/A43S15.mp3"),
      correctAnswer: "January is the hottest month here.",
      successTitle: "Correto",
      successMessage: "January is the hottest month here.",
    },
  },
  {
    key: "a2ic43s16",
    component: "Exercise16",
    activity: {
      prompt: "Gravação de áudio",
      image: Images.ex16,
      tipButtonLabel: "Tip",
      instruction: 'Pronuncie: "This is the biggest house on the street!"',
      helperText: "This is the biggest house on the street!",
      successTitle: "Muito bem!",
      successMessage: "Seu áudio foi gravado.",
    },
  },
  {
    key: "a2ic43s17",
    component: "Exercise17",
    activity: {
      label: "Final",
      content: [
        "/blue{Ortografia Dominada!}",
        "Agora você escreve superlativos como um profissional. O Y e o CVC não te enganam mais.",
      ],
      continueLabel: "Concluir",
    },
  },
];

export default createA2LessonScreen(LESSON_SLIDES);
