import createA2LessonScreen from "./A2LessonScreen";
import { ICA2 } from "../../../../util/images";

const LESSON_SLIDES = [
  {
    key: "a2ic42s1",
    component: "Exercise17",
    activity: {
      label: "MÓDULO 5 • AULA 42",
      content: [
        "/blue{I'm the fastest one.}",
        "/blue{O Sufixo do Campeão: -EST}",
        'Quando o adjetivo é curtinho, não usamos "most". Colocamos THE na frente e grudamos -EST no final.',
        "Fórmula: THE + adjetivo + EST.",
        "Tall → The tallest.",
      ],
      continueLabel: "Continuar",
    },
  },
  {
    key: "a2ic42s2",
    component: "Exercise14",
    needsSpeech: true,
    activity: {
      prompt: "Escute e escolha.",
      image: ICA2.A42S2,
      audioSource: require("../../../../../mp3/IC/A2/A42S2.mp3"),
      audioText: "The tallest",
      options: ["The tallest", "The most tall"],
      correctAnswer: "The tallest",
      correctOption: "The tallest",
      feedbackMessage: "Tall vira the tallest.",
      successTitle: "Correto",
    },
  },
  {
    key: "a2ic42s3",
    component: "Exercise14",
    needsSpeech: true,
    activity: {
      prompt: "Escute e escolha.",
      image: ICA2.A42S3,
      audioSource: require("../../../../../mp3/IC/A2/A42S3.mp3"),
      audioText: "The fastest",
      options: ["The fast", "The fastest"],
      correctAnswer: "The fastest",
      correctOption: "The fastest",
      feedbackMessage: "Fast vira the fastest.",
      successTitle: "Correto",
    },
  },
  {
    key: "a2ic42s4",
    component: "Exercise14",
    needsSpeech: true,
    activity: {
      prompt: "Escute e escolha.",
      image: ICA2.A42S4,
      audioSource: require("../../../../../mp3/IC/A2/A42S4.mp3"),
      audioText: "The oldest",
      options: ["The newest", "The oldest"],
      correctAnswer: "The oldest",
      correctOption: "The oldest",
      feedbackMessage: "Old vira the oldest.",
      successTitle: "Correto",
    },
  },
  {
    key: "a2ic42s5",
    component: "Exercise14",
    needsSpeech: true,
    activity: {
      prompt: "Escute e escolha.",
      image: ICA2.A42S5,
      audioSource: require("../../../../../mp3/IC/A2/A42S5.mp3"),
      audioText: "The coldest",
      options: ["The coldest", "The colder"],
      correctAnswer: "The coldest",
      correctOption: "The coldest",
      feedbackMessage: "Cold vira the coldest.",
      successTitle: "Correto",
    },
  },
  {
    key: "a2ic42s6",
    component: "Exercise13",
    needsSpeech: true,
    activity: {
      prompt: 'Escreva "o mais rápido".',
      audioSource: require("../../../../../mp3/IC/A2/A42S6.mp3"),
      audioText: "Fastest",
      letters: ["F", "A", "S", "T", "E", "S", "T"],
      correctWord: "FASTEST",
      successTitle: "Correto",
      successMessage: "Fastest.",
    },
  },
  {
    key: "a2ic42s7",
    component: "Exercise13",
    needsSpeech: true,
    activity: {
      prompt: 'Escreva "o mais alto".',
      audioSource: require("../../../../../mp3/IC/A2/A42S7.mp3"),
      audioText: "Tallest",
      letters: ["T", "A", "L", "L", "E", "S", "T"],
      correctWord: "TALLEST",
      successTitle: "Correto",
      successMessage: "Tallest.",
    },
  },
  {
    key: "a2ic42s8",
    component: "Exercise13",
    needsSpeech: true,
    activity: {
      prompt: 'Escreva "o mais velho".',
      audioSource: require("../../../../../mp3/IC/A2/A42S8.mp3"),
      audioText: "Oldest",
      letters: ["O", "L", "D", "E", "S", "T"],
      correctWord: "OLDEST",
      successTitle: "Correto",
      successMessage: "Oldest.",
    },
  },
  {
    key: "a2ic42s9",
    component: "Exercise6",
    activity: {
      prompt: '"O Everest é a montanha mais alta."',
      words: ["Mount Everest", "is", "the highest", "mountain", "."],
      correctOrder: ["Mount Everest", "is", "the highest", "mountain", "."],
      successTitle: "Correto",
      successMessage: "Mount Everest is the highest mountain.",
    },
  },
  {
    key: "a2ic42s10",
    component: "Exercise6",
    activity: {
      prompt: '"A Rússia é o maior país."',
      words: ["Russia", "is", "the largest", "country", "."],
      correctOrder: ["Russia", "is", "the largest", "country", "."],
      successTitle: "Correto",
      successMessage: "Russia is the largest country.",
    },
  },
  {
    key: "a2ic42s11",
    component: "Exercise6",
    activity: {
      prompt: '"Janeiro é o mês mais frio aqui."',
      words: ["January", "is", "the coldest", "month", "here", "."],
      correctOrder: ["January", "is", "the coldest", "month", "here", "."],
      successTitle: "Correto",
      successMessage: "January is the coldest month here.",
    },
  },
  {
    key: "a2ic42s12",
    component: "Exercise5",
    activity: {
      prompt: 'Use o superlativo de "tall".',
      image: ICA2.A42S12,
      sentenceStart: "The giraffe is",
      sentenceEnd: "animal in the world.",
      options: ["the tallest", "taller"],
      correctAnswer: "the tallest",
      successTitle: "Correto",
      successMessage: "The tallest é superlativo.",
    },
  },
  {
    key: "a2ic42s13",
    component: "Exercise5",
    activity: {
      prompt: 'Use o superlativo de "old".',
      image: ICA2.A42S13,
      sentenceStart: "My grandma is",
      sentenceEnd: "person in my family.",
      options: ["the youngest", "the oldest"],
      correctAnswer: "the oldest",
      successTitle: "Correto",
      successMessage: "Old vira the oldest.",
    },
  },
  {
    key: "a2ic42s14",
    component: "Exercise11",
    activity: {
      words: [
        "the longest",
        "the youngest",
        "the cleanest",
        "the darkest",
        "the nearest",
      ],
      secondsPerWord: 5,
    },
  },
  {
    key: "a2ic42s15",
    component: "Exercise19",
    activity: {
      prompt: "Escute e digite.",
      audioSource: require("../../../../../mp3/IC/A2/A42S15.mp3"),
      audioText: "This is the cheapest phone in the store.",
      correctAnswer: "This is the cheapest phone in the store.",
      successTitle: "Correto",
      successMessage: "This is the cheapest phone in the store.",
    },
  },
  {
    key: "a2ic42s16",
    component: "Exercise19",
    activity: {
      prompt: "Escute e digite.",
      audioSource: require("../../../../../mp3/IC/A2/A42S16.mp3"),
      audioText: "Today is the shortest day of the year.",
      correctAnswer: "Today is the shortest day of the year.",
      successTitle: "Correto",
      successMessage: "Today is the shortest day of the year.",
    },
  },
  {
    key: "a2ic42s17",
    component: "Exercise16",
    activity: {
      prompt: "Gravação de áudio",
      instruction: 'Grave: "I am the fastest student in the Lingueto app!"',
      helperText: "I am the fastest student in the Lingueto app!",
      successTitle: "Muito bem!",
      successMessage: "Seu áudio foi gravado.",
    },
  },
  {
    key: "a2ic42s18",
    component: "Exercise17",
    activity: {
      label: "Final",
      content: [
        "/blue{Recordista de Adjetivos Curtos!}",
        "Você aprendeu a transformar palavras pequenas em superlativos gigantes.",
      ],
      continueLabel: "Concluir",
    },
  },
];

export default createA2LessonScreen(LESSON_SLIDES);
