import createA2LessonScreen from "./A2LessonScreen";
import { ICA2 } from "../../../../util/images";

const PICNIC_AUDIO =
  "Hi! I'm Sabrina. I'm sitting in the park right now. It's a beautiful day! My brother, Leo, is running near the lake. My parents are eating sandwiches on the grass. Oh, look! A small dog is chasing a ball. It's so cute! My sister is taking photos of everyone. I'm wearing my green hat and I'm drinking cold juice. My friends are arriving now. We're starting a big picnic!";

const LESSON_SLIDES = [
  {
    key: "a2ic05s1",
    component: "Exercise17",
    activity: {
      label: "MÓDULO 1 • AULA 5",
      content: [
        "/blue{Sabrina’s Picnic}",
        "",
        "Imagine que você está ouvindo uma mensagem de voz de um amigo em um lugar incrível. As palavras dele pintam o quadro na sua mente.",
        "",
        "/blue{Tip - O Som da Cena}",
        "Em diálogos reais, as pessoas usam contrações: I'm, He's, They're.",
        "Foque nas palavras terminadas em -ING. Elas são as estrelas da ação.",
      ],
      continueLabel: "Continuar",
    },
  },
  {
    key: "a2ic05s2",
    type: "listenOnly",
    activity: {
      prompt: "Ouça o áudio principal",
      image: ICA2.A5S2,
      audioSource: require("../../../../../mp3/IC/A2/A5S2.mp3"),
      transcript: PICNIC_AUDIO,
      continueLabel: "Continuar",
    },
  },
  ...[
    [
      "a2ic05s3",
      "Onde a Sabrina está agora?",
      "Sabrina is",
      "at the park.",
      ["sitting", "sit"],
      "sitting",
      "Sabrina is sitting at the park.",
    ],
    [
      "a2ic05s4",
      "O que a Sabrina está fazendo no início?",
      "She is",
      "on a bench.",
      ["sitting", "running"],
      "sitting",
      "She is sitting on a bench.",
    ],
    [
      "a2ic05s5",
      "O que o Leo está fazendo?",
      "Leo is",
      "near the lake.",
      ["running", "runing"],
      "running",
      "Leo is running near the lake.",
    ],
    [
      "a2ic05s6",
      "Onde o Leo está correndo?",
      "He is running near the",
      ".",
      ["lake", "kitchen"],
      "lake",
      "He is running near the lake.",
    ],
    [
      "a2ic05s7",
      "O que os pais da Sabrina estão fazendo?",
      "They are",
      "lunch.",
      ["eating", "eat"],
      "eating",
      "They are eating lunch.",
    ],
    [
      "a2ic05s8",
      "O que o cachorro está fazendo?",
      "The dog is",
      "a ball.",
      ["chasing", "chaseing"],
      "chasing",
      "Chase perde o E: chasing.",
    ],
    [
      "a2ic05s9",
      "Qual é a ação da irmã da Sabrina?",
      "She is",
      "photos.",
      ["taking", "takeing"],
      "taking",
      "Take perde o E: taking.",
    ],
    [
      "a2ic05s10",
      "O que a Sabrina está vestindo?",
      "She is wearing",
      "jeans.",
      ["blue", "red"],
      "blue",
      "She is wearing blue jeans.",
    ],
    [
      "a2ic05s11",
      "O que a Sabrina está bebendo?",
      "She is drinking",
      "juice.",
      ["cold", "hot"],
      "cold",
      "She is drinking cold juice.",
    ],
    [
      "a2ic05s12",
      "O que vai acontecer agora com os amigos?",
      "They are",
      "a picnic.",
      ["starting", "start"],
      "starting",
      "They are starting a picnic.",
    ],
  ].map(
    ([
      key,
      prompt,
      sentenceStart,
      sentenceEnd,
      options,
      correctAnswer,
      successMessage,
    ]) => ({
      key,
      component: "Exercise5",
      activity: {
        prompt,
        image: ICA2.A5S13,
        sentenceStart,
        sentenceEnd,
        options,
        correctAnswer,
        successTitle: "Correto",
        successMessage,
      },
    }),
  ),
  {
    key: "a2ic05s13",
    component: "Exercise3",
    needsSpeech: true,
    activity: {
      prompt: "De acordo com o áudio, verdadeiro ou falso?",
      image: ICA2.A5S13,
      audioText: "My parents are eating sandwiches on the grass.",
      statement:
        "De acordo com o áudio, os pais da Sabrina estão comendo pizza.",
      textOnScreen: "Os pais da Sabrina estão comendo pizza.",
      options: ["true", "false"],
      correctAnswer: "false",
      successTitle: "Correto",
      successMessage: "False. O áudio diz que eles estão comendo sandwiches.",
      feedbackMessage: "O alimento mencionado foi sandwiches, não pizza.",
    },
  },
  {
    key: "a2ic05s14",
    component: "Exercise6",
    activity: {
      prompt: "Monte a frase que descreve a Sabrina no final do áudio:",
      words: ["juice.", "Sabrina", "drinking", "is", "cold"],
      correctOrder: ["Sabrina", "is", "drinking", "cold", "juice."],
      successTitle: "Correto",
      successMessage: "Sabrina is drinking cold juice.",
    },
  },
  {
    key: "a2ic05s15",
    component: "Exercise11",
    activity: {
      prompt: "Digite estes verbos do áudio com -ING:",
      title: "Escreva a forma com -ING",
      placeholder: "Digite aqui",
      secondsPerWord: 8,
      words: ["Sitting", "Running", "Eating", "Taking", "Arriving"],
      successTitle: "Correto",
      successMessage: "Você capturou as ações do piquenique.",
    },
  },
];

export default createA2LessonScreen(LESSON_SLIDES);
