import createA2LessonScreen from "./A2LessonScreen";
import { ICA2 } from "../../../../util/images";

const LESSON_SLIDES = [
  {
    key: "a2ic37s1",
    component: "Exercise17",
    activity: {
      label: "MÓDULO 4 • AULA 37",
      content: [
        "/blue{My car is better!}",
        "/blue{Regras? Não para eles!}",
        "Alguns adjetivos são rebeldes e mudam completamente quando comparamos.",
        "Não use -er nem more. Memorize: Good → Better, Bad → Worse, Far → Farther/Further.",
      ],
      continueLabel: "Continuar",
    },
  },
  {
    key: "a2ic37s2",
    component: "Exercise14",
    needsSpeech: true,
    activity: {
      prompt: "Escute e escolha.",
      image: ICA2.A37S2,
      audioSource: require("../../../../../mp3/IC/A2/A37S2.mp3"),
      audioText: "Better",
      options: ["Gooder", "Better"],
      correctAnswer: "Better",
      correctOption: "Better",
      feedbackMessage: "Good vira better. Gooder não existe.",
      successTitle: "Correto",
    },
  },
  {
    key: "a2ic37s3",
    component: "Exercise13",
    needsSpeech: true,
    activity: {
      prompt: 'Escreva "melhor" em inglês.',
      audioSource: require("../../../../../mp3/IC/A2/A37S3.mp3"),
      audioText: "Better",
      letters: ["B", "E", "T", "T", "E", "R"],
      correctWord: "BETTER",
      successTitle: "Correto",
      successMessage: "Better.",
    },
  },
  {
    key: "a2ic37s4",
    component: "Exercise5",
    activity: {
      prompt: "Dê sua opinião sobre sabores.",
      image: ICA2.A37S4,
      sentenceStart: "Chocolate is",
      sentenceEnd: "than vanilla.",
      options: ["better", "taller"],
      correctAnswer: "better",
      successTitle: "Correto",
      successMessage: "Better é o comparativo de good.",
    },
  },
  {
    key: "a2ic37s5",
    component: "Exercise14",
    needsSpeech: true,
    activity: {
      prompt: "Escute e escolha.",
      image: ICA2.A37S5,
      audioSource: require("../../../../../mp3/IC/A2/A37S5.mp3"),
      audioText: "Worse",
      options: ["Badder", "Worse"],
      correctAnswer: "Worse",
      correctOption: "Worse",
      feedbackMessage: "Bad vira worse. Badder não existe.",
      successTitle: "Correto",
    },
  },
  {
    key: "a2ic37s6",
    component: "Exercise13",
    needsSpeech: true,
    activity: {
      prompt: 'Escreva "pior" em inglês.',
      audioSource: require("../../../../../mp3/IC/A2/A37S6.mp3"),
      audioText: "Worse",
      letters: ["W", "O", "R", "S", "E"],
      correctWord: "WORSE",
      successTitle: "Correto",
      successMessage: "Worse.",
    },
  },
  {
    key: "a2ic37s7",
    component: "Exercise6",
    activity: {
      prompt: "Organize a comparação.",
      words: ["Being sick", "is", "worse", "than", "being tired", "."],
      correctOrder: ["Being sick", "is", "worse", "than", "being tired", "."],
      successTitle: "Correto",
      successMessage: "Being sick is worse than being tired.",
    },
  },
  {
    key: "a2ic37s8",
    component: "Exercise14",
    needsSpeech: true,
    activity: {
      prompt: "Escute e escolha.",
      image: ICA2.A37S8,
      audioSource: require("../../../../../mp3/IC/A2/A37S8.mp3"),
      audioText: "Farther",
      options: ["Far", "Farther"],
      correctAnswer: "Farther",
      correctOption: "Farther",
      feedbackMessage: "Farther é usado para distância física.",
      successTitle: "Correto",
    },
  },
  {
    key: "a2ic37s9",
    component: "Exercise14",
    needsSpeech: true,
    activity: {
      prompt: "Escute e escolha.",
      image: ICA2.A37S9,
      audioSource: require("../../../../../mp3/IC/A2/A37S9.mp3"),
      audioText: "Further",
      options: ["Farther", "Further"],
      correctAnswer: "Further",
      correctOption: "Further",
      feedbackMessage: "Further pode ser usado em sentido figurado ou abstrato.",
      successTitle: "Correto",
    },
  },
  {
    key: "a2ic37s10",
    component: "Exercise17",
    activity: {
      label: "Tabela",
      content: [
        "/blue{O Mapa dos Rebeldes}",
        "Good → Better (melhor)",
        "Bad → Worse (pior)",
        "Far → Farther / Further (mais longe)",
      ],
      continueLabel: "Continuar",
    },
  },
  {
    key: "a2ic37s11",
    component: "Exercise19",
    activity: {
      prompt: "Escute a frase e digite com atenção.",
      audioSource: require("../../../../../mp3/IC/A2/A37S11.mp3"),
      audioText: "Health is better than money.",
      correctAnswer: "Health is better than money.",
      successTitle: "Correto",
      successMessage: "Health is better than money.",
    },
  },
  {
    key: "a2ic37s12",
    component: "Exercise16",
    activity: {
      prompt: "Gravação de áudio",
      instruction: 'Grave uma preferência usando "better than".',
      helperText: 'Exemplo: "Fruits are better than candy!"',
      successTitle: "Muito bem!",
      successMessage: "Seu áudio foi gravado.",
    },
  },
  {
    key: "a2ic37s13",
    component: "Exercise17",
    activity: {
      label: "Final",
      content: [
        "/blue{Desafio Concluído!}",
        "Você venceu os irregulares. Eles são poucos, então agora vai ficar fácil identificar em qualquer lugar.",
      ],
      continueLabel: "Concluir",
    },
  },
];

export default createA2LessonScreen(LESSON_SLIDES);
