import React from "react";
import CourseOverviewScreen from "../../CourseOverviewScreen";

export const INGLES_COMPLETO_STORAGE_KEY = "@progesso_ingles_completo_A2";
export const INGLES_COMPLETO_COURSE_NAME = "Inglês Completo";

export const inglesModuleDefs = [
  {
    id: 0,
    name: "Present Continuous",
    subtitle: "Aulas A2IC01 até A2IC10",
    locked: false,
    accent: "#6C63FF",
    icon: "check",
  },
  {
    id: 1,
    name: "Simple Past",
    subtitle: "Aulas A2IC11 até A2IC22",
    locked: false,
    accent: "#6C63FF",
    icon: "check",
  },
  {
    id: 2,
    name: "Past continuous",
    subtitle: "Aulas A2IC23 até A2IC34",
    locked: false,
    accent: "#6C63FF",
    icon: "check",
  },
  {
    id: 3,
    name: "Comparatives",
    subtitle: "Aulas A2IC35 até A2IC40",
    locked: false,
    accent: "#6C63FF",
    icon: "check",
  },
  {
    id: 4,
    name: "Superlatives",
    subtitle: "Aulas A2IC41 até A2IC45",
    locked: false,
    accent: "#6C63FF",
    icon: "check",
  },
];

export const inglesSampleLessons = [
  { module: 0, id: "1", title: "I am working", type: "Aula", screen: "A2IC01" },
  {
    module: 0,
    id: "2",
    title: "Part 2",
    type: "Aula",
    screen: "A2IC02",
  },
  {
    module: 0,
    id: "3",
    title: "Making phrases",
    type: "Aula",
    screen: "A2IC03",
  },
  {
    module: 0,
    id: "4",
    title: "Sabrina's Blog",
    type: "Aula",
    screen: "A2IC04",
  },
  {
    module: 0,
    id: "5",
    title: "Sabrina's Picnic",
    type: "Aula",
    screen: "A2IC05",
  },
  {
    module: 0,
    id: "6",
    title: "Are you studying?",
    type: "Aula",
    screen: "A2IC06",
  },
  {
    module: 0,
    id: "7",
    title: "Are you writing?",
    type: "Aula",
    screen: "A2IC07",
  },
  {
    module: 0,
    id: "8",
    title: "She isn't sleeping",
    type: "Aula",
    screen: "A2IC08",
  },
  {
    module: 0,
    id: "9",
    title: "I'm working tomorrow",
    type: "Aula",
    screen: "A2IC09",
  },
  {
    module: 0,
    id: "10",
    title: "Do or doing?",
    type: "Aula",
    screen: "A2IC10",
  },
  {
    module: 1,
    id: "11",
    title: "I studied last night",
    type: "Aula",
    screen: "A2IC11",
  },
  {
    module: 1,
    id: "12",
    title: "I worked yesterday",
    type: "Aula",
    screen: "A2IC12",
  },
  {
    module: 1,
    id: "13",
    title: "I took a shower",
    type: "Aula",
    screen: "A2IC13",
  },
  {
    module: 1,
    id: "14",
    title: "I took a shower",
    type: "Aula",
    screen: "A2IC14",
  },
  {
    module: 1,
    id: "15",
    title: "Regular and irregular",
    type: "Aula",
    screen: "A2IC15",
  },
  {
    module: 1,
    id: "16",
    title: "I didn't study",
    type: "Aula",
    screen: "A2IC16",
  },
  {
    module: 1,
    id: "17",
    title: "I didn't go!",
    type: "Aula",
    screen: "A2IC17",
  },
  {
    module: 1,
    id: "18",
    title: "Did you study?",
    type: "Aula",
    screen: "A2IC18",
  },
  {
    module: 1,
    id: "19",
    title: "Did you see it?",
    type: "Aula",
    screen: "A2IC19",
  },
  {
    module: 1,
    id: "20",
    title: "Did you work?",
    type: "Aula",
    screen: "A2IC20",
  },
  {
    module: 1,
    id: "21",
    title: "Nice concert!",
    type: "Aula",
    screen: "A2IC21",
  },
  {
    module: 1,
    id: "22",
    title: "First/then/finally",
    type: "Aula",
    screen: "A2IC22",
  },
  {
    module: 2,
    id: "23",
    title: "I was sleeping",
    type: "Aula",
    screen: "A2IC23",
  },
  {
    module: 2,
    id: "24",
    title: "You were working",
    type: "Aula",
    screen: "A2IC24",
  },
  {
    module: 2,
    id: "25",
    title: "I wasn't writing",
    type: "Aula",
    screen: "A2IC25",
  },
  {
    module: 2,
    id: "26",
    title: "Was he sleeping?",
    type: "Aula",
    screen: "A2IC26",
  },
  {
    module: 2,
    id: "27",
    title: "Final combo",
    type: "Aula",
    screen: "A2IC27",
  },
  {
    module: 2,
    id: "28",
    title: "ING or ED?",
    type: "Aula",
    screen: "A2IC28",
  },
  {
    module: 2,
    id: "29",
    title: "Carol's Saturday",
    type: "Aula",
    screen: "A2IC29",
  },
  {
    module: 2,
    id: "30",
    title: "Where's my cake?",
    type: "Aula",
    screen: "A2IC30",
  },
  {
    module: 2,
    id: "31",
    title: "Booking a flight",
    type: "Aula",
    screen: "A2IC31",
  },
  {
    module: 2,
    id: "32",
    title: "Hotel",
    type: "Aula",
    screen: "A2IC32",
  },
  {
    module: 2,
    id: "33",
    title: "Let's go sightseeing",
    type: "Aula",
    screen: "A2IC33",
  },
  {
    module: 2,
    id: "34",
    title: "Where can I...?",
    type: "Aula",
    screen: "A2IC34",
  },
  {
    module: 3,
    id: "35",
    title: "It's more beautiful!",
    type: "Aula",
    screen: "A2IC35",
  },
  {
    module: 3,
    id: "36",
    title: "It's hotter today!",
    type: "Aula",
    screen: "A2IC36",
  },
  {
    module: 3,
    id: "37",
    title: "My car is better!",
    type: "Aula",
    screen: "A2IC37",
  },
  {
    module: 3,
    id: "38",
    title: "It's much better now!",
    type: "Aula",
    screen: "A2IC38",
  },
  {
    module: 3,
    id: "39",
    title: "He's as tall as me!",
    type: "Aula",
    screen: "A2IC39",
  },
  {
    module: 3,
    id: "40",
    title: "Julia's family!",
    type: "Aula",
    screen: "A2IC40",
  },
  {
    module: 4,
    id: "41",
    title: "It's the most...",
    type: "Aula",
    screen: "A2IC41",
  },
  {
    module: 4,
    id: "42",
    title: "I'm the fastest one.",
    type: "Aula",
    screen: "A2IC42",
  },
  {
    module: 4,
    id: "43",
    title: "I'm the fastest one.",
    type: "Aula",
    screen: "A2IC43",
  },
  {
    module: 4,
    id: "44",
    title: "I'm the best",
    type: "Aula",
    screen: "A2IC44",
  },
  {
    module: 4,
    id: "45",
    title: "The talent show",
    type: "Aula",
    screen: "A2IC45",
  },
];

export default function InglesCompletoScreen(props) {
  return (
    <CourseOverviewScreen
      {...props}
      courseName={INGLES_COMPLETO_COURSE_NAME}
      storageKey={INGLES_COMPLETO_STORAGE_KEY}
      moduleDefs={inglesModuleDefs}
      lessons={inglesSampleLessons}
    />
  );
}
