import React from "react";
import CourseOverviewScreen from "../../CourseOverviewScreen";

export const INGLES_COMPLETO_STORAGE_KEY = "@progesso_ingles_completo_B1";
export const INGLES_COMPLETO_COURSE_NAME = "Inglês Completo";

export const inglesModuleDefs = [
  {
    id: 0,
    name: "Present Perfect",
    subtitle: "Aulas B1IC01 até B1IC05",
    locked: false,
    accent: "#6C63FF",
    icon: "check",
  },
  {
    id: 1,
    name: "Work & Modern Careers",
    subtitle: "Aulas B1IC06 até B1IC10",
    locked: false,
    accent: "#6C63FF",
    icon: "check",
  },
  {
    id: 2,
    name: "Hypothetical Situations",
    subtitle: "Aulas B1IC11 até B1IC14",
    locked: false,
    accent: "#6C63FF",
    icon: "check",
  },
  {
    id: 3,
    name: "Socializing & Small Talk",
    subtitle: "Aulas B1IC15 até B1IC20",
    locked: false,
    accent: "#6C63FF",
    icon: "check",
  },
  {
    id: 4,
    name: "Rules, Permissions & Obligations",
    subtitle: "Aulas B1IC21 ate B1IC24",
    locked: false,
    accent: "#6C63FF",
    icon: "check",
  },
  {
    id: 5,
    name: "Narrative Tenses (Mastering Stories)",
    subtitle: "Aulas B1IC25 ate B1IC28",
    locked: false,
    accent: "#6C63FF",
    icon: "check",
  },
  {
    id: 6,
    name: "The Passive Voice (Focus on Information)",
    subtitle: "Aulas B1IC29 até B1IC31",
    locked: false,
    accent: "#6C63FF",
    icon: "check",
  },
  {
    id: 7,
    name: "Advanced Phrasal Verbs & Idioms",
    subtitle: "Aulas B1IC32 até B1IC35",
    locked: false,
    accent: "#6C63FF",
    icon: "check",
  },
  {
    id: 8,
    name: "Speculating About the Past (Modal Verbs 4)",
    subtitle: "Aulas B1IC36 até B1IC38",
    locked: false,
    accent: "#6C63FF",
    icon: "check",
  },
  {
    id: 9,
    name: "Linking Words for Contrast",
    subtitle: "Aula B1IC39",
    locked: false,
    accent: "#6C63FF",
    icon: "check",
  },
];

export const inglesSampleLessons = [
  {
    module: 0,
    id: "1",
    title: "Since I was...",
    type: "Aula",
    screen: "B1IC01",
  },
  { module: 0, id: "2", title: "Not yet!", type: "Aula", screen: "B1IC02" },
  {
    module: 0,
    id: "3",
    title: "I've been studying!",
    type: "Aula",
    screen: "B1IC03",
  },
  {
    module: 0,
    id: "4",
    title: "What've you been up to?",
    type: "Aula",
    screen: "B1IC04",
  },
  {
    module: 0,
    id: "5",
    title: "'ve been doing / have done",
    type: "Aula",
    screen: "B1IC05",
  },
  { module: 1, id: "6", title: "Strengths", type: "Aula", screen: "B1IC06" },
  {
    module: 1,
    id: "7",
    title: "Hello dear,",
    type: "Aula",
    screen: "B1IC07",
  },
  { module: 1, id: "8", title: "Deadline", type: "Aula", screen: "B1IC08" },
  {
    module: 1,
    id: "9",
    title: "Hustle Culture",
    type: "Aula",
    screen: "B1IC09",
  },
  {
    module: 1,
    id: "10",
    title: "Founder, Visionary, Legacy",
    type: "Aula",
    screen: "B1IC10",
  },
  { module: 2, id: "11", title: "If I won", type: "Aula", screen: "B1IC11" },
  {
    module: 2,
    id: "12",
    title: "If I were you",
    type: "Aula",
    screen: "B1IC12",
  },
  {
    module: 2,
    id: "13",
    title: "What would you do if...",
    type: "Aula",
    screen: "B1IC13",
  },
  {
    module: 2,
    id: "14",
    title: "I wish I had...",
    type: "Aula",
    screen: "B1IC14",
  },
  {
    module: 3,
    id: "15",
    title: "Keep talking",
    type: "Aula",
    screen: "B1IC15",
  },
  {
    module: 3,
    id: "16",
    title: "I see your point, but...",
    type: "Aula",
    screen: "B1IC16",
  },
  { module: 3, id: "17", title: "Clarifying", type: "Aula", screen: "B1IC17" },
  {
    module: 3,
    id: "18",
    title: "Breaking the ice",
    type: "Aula",
    screen: "B1IC18",
  },
  {
    module: 3,
    id: "19",
    title: 'Beyond "how are you?"',
    type: "Aula",
    screen: "B1IC19",
  },
  {
    module: 3,
    id: "20",
    title: "Did you know?",
    type: "Aula",
    screen: "B1IC20",
  },
  {
    module: 4,
    id: "21",
    title: "Must vs. Have to",
    type: "Aula",
    screen: "B1IC21",
  },
  {
    module: 4,
    id: "22",
    title: "Can't vs. Mustn't",
    type: "Aula",
    screen: "B1IC22",
  },
  {
    module: 4,
    id: "23",
    title: "Don't have to",
    type: "Aula",
    screen: "B1IC23",
  },
  {
    module: 4,
    id: "24",
    title: "Permission in different contexts",
    type: "Aula",
    screen: "B1IC24",
  },
  {
    module: 5,
    id: "25",
    title: "Past Perfect",
    type: "Aula",
    screen: "B1IC25",
  },
  {
    module: 5,
    id: "26",
    title: "Past Perfect Continuous",
    type: "Aula",
    screen: "B1IC26",
  },
  {
    module: 5,
    id: "27",
    title: "Combining Tenses",
    type: "Aula",
    screen: "B1IC27",
  },
  {
    module: 5,
    id: "28",
    title: "Narrative fillers",
    type: "Aula",
    screen: "B1IC28",
  },
  {
    module: 6,
    id: "29",
    title: "It's said that",
    type: "Aula",
    screen: "B1IC29",
  },
  {
    module: 6,
    id: "30",
    title: "It's produced in...",
    type: "Aula",
    screen: "B1IC30",
  },
  {
    module: 6,
    id: "31",
    title: "I'd like to have my car fixed",
    type: "Aula",
    screen: "B1IC31",
  },
  { module: 7, id: "32", title: "Carry out", type: "Aula", screen: "B1IC32" },
  { module: 7, id: "33", title: "Time flies", type: "Aula", screen: "B1IC33" },
  {
    module: 7,
    id: "34",
    title: '"Do" vs. "Make"',
    type: "Aula",
    screen: "B1IC34",
  },
  {
    module: 7,
    id: "35",
    title: "Separable vs. Inseparable Phrasal Verbs",
    type: "Aula",
    screen: "B1IC35",
  },
  {
    module: 8,
    id: "36",
    title: "You should have told me",
    type: "Aula",
    screen: "B1IC36",
  },
  {
    module: 8,
    id: "37",
    title: "He must have forgotten",
    type: "Aula",
    screen: "B1IC37",
  },
  {
    module: 8,
    id: "38",
    title: "Couldn't have",
    type: "Aula",
    screen: "B1IC38",
  },
  {
    module: 9,
    id: "39",
    title: 'Linking Words for Contrast: "However", "Nevertheless", "Despite"',
    type: "Aula",
    screen: "B1IC39",
  },
];

export default function InglesCompletoScreen(props) {
  return (
    <CourseOverviewScreen
      {...props}
      courseName={INGLES_COMPLETO_COURSE_NAME}
      storageKey={INGLES_COMPLETO_STORAGE_KEY}
      moduleDefs={inglesModuleDefs}
      lessons={inglesSampleLessons}
    />
  );
}
