export const INGLES_COMPLETO_STORAGE_KEY = "@progesso_ingles_completo";

export const inglesModuleDefs = [
  {
    id: 0,
    name: "Foundations",
    subtitle: "Basic grammar and vocabulary",
    locked: false,
    accent: "#26BA86",
    icon: "check",
  },
  {
    id: 1,
    name: "Greetings and Small Talk",
    subtitle: "Introduce yourself naturally",
    locked: false,
    accent: "#B8C2CF",
    icon: "lock-outline",
  },
  {
    id: 2,
    name: "Presenting Your Company",
    subtitle: "Professional introductions",
    locked: true,
    accent: "#B8C2CF",
    icon: "lock-outline",
  },
  {
    id: 3,
    name: "Office Vocabulary",
    subtitle: "Common words and situations",
    locked: true,
    accent: "#B8C2CF",
    icon: "lock-outline",
  },
  {
    id: 4,
    name: "Professional Emails",
    subtitle: "Write clear messages",
    locked: true,
    accent: "#B8C2CF",
    icon: "lock-outline",
  },
  {
    id: 5,
    name: "Meetings and Agenda",
    subtitle: "Speak with confidence at work",
    locked: true,
    accent: "#B8C2CF",
    icon: "lock-outline",
  },
];

export const inglesSampleLessons = [
  { module: 0, id: "1", title: "IC01", type: "Aula", screen: "IC01" },
  { module: 0, id: "2", title: "IC02", type: "Aula", screen: "IC02" },
  { module: 0, id: "3", title: "IC03", type: "Aula", screen: "IC03" },
  { module: 0, id: "4", title: "IC04", type: "Aula", screen: "IC04" },
  { module: 0, id: "5", title: "IC05", type: "Aula", screen: "IC05" },
  { module: 0, id: "6", title: "IC06", type: "Aula", screen: "IC06" },
  { module: 0, id: "7", title: "IC07", type: "Aula", screen: "IC07" },
  { module: 0, id: "8", title: "IC08", type: "Aula", screen: "IC08" },
  { module: 0, id: "9", title: "IC09", type: "Aula", screen: "IC09" },
  { module: 0, id: "10", title: "IC10", type: "Aula", screen: "IC10" },
  { module: 0, id: "11", title: "IC11", type: "Aula", screen: "IC11" },
  { module: 0, id: "12", title: "IC12", type: "Aula", screen: "IC12" },
  { module: 0, id: "13", title: "IC13", type: "Aula", screen: "IC13" },
  { module: 0, id: "14", title: "IC14", type: "Aula", screen: "IC14" },
  { module: 0, id: "15", title: "IC15", type: "Aula", screen: "IC15" },
];
